//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BugsnagBreadcrumbs, BugsnagMetaData, NSArray, NSMutableArray, NSString, NSURL;

@interface BugsnagConfiguration : NSObject
{
    _Bool _automaticallyCollectBreadcrumbs;
    _Bool _autoNotify;
    NSString *_apiKey;
    NSURL *_notifyURL;
    NSString *_releaseStage;
    NSArray *_notifyReleaseStages;
    NSString *_context;
    NSString *_appVersion;
    BugsnagMetaData *_metaData;
    BugsnagMetaData *_config;
    BugsnagBreadcrumbs *_breadcrumbs;
    NSArray *_beforeSendBlocks;
    CDUnknownFunctionPointerType _onCrashHandler;
    NSMutableArray *_beforeNotifyHooks;
    NSMutableArray *_BugsnagBeforeSendBlock;
}

@property(retain, nonatomic) NSMutableArray *BugsnagBeforeSendBlock; // @synthesize BugsnagBeforeSendBlock=_BugsnagBeforeSendBlock;
@property(retain, nonatomic) NSMutableArray *beforeNotifyHooks; // @synthesize beforeNotifyHooks=_beforeNotifyHooks;
@property(nonatomic) _Bool autoNotify; // @synthesize autoNotify=_autoNotify;
@property(nonatomic) CDUnknownFunctionPointerType onCrashHandler; // @synthesize onCrashHandler=_onCrashHandler;
@property(readonly, nonatomic) NSArray *beforeSendBlocks; // @synthesize beforeSendBlocks=_beforeSendBlocks;
@property(nonatomic) _Bool automaticallyCollectBreadcrumbs; // @synthesize automaticallyCollectBreadcrumbs=_automaticallyCollectBreadcrumbs;
@property(readonly, nonatomic) BugsnagBreadcrumbs *breadcrumbs; // @synthesize breadcrumbs=_breadcrumbs;
@property(retain, nonatomic) BugsnagMetaData *config; // @synthesize config=_config;
@property(retain, nonatomic) BugsnagMetaData *metaData; // @synthesize metaData=_metaData;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSString *context; // @synthesize context=_context;
@property(retain, nonatomic) NSArray *notifyReleaseStages; // @synthesize notifyReleaseStages=_notifyReleaseStages;
@property(retain, nonatomic) NSString *releaseStage; // @synthesize releaseStage=_releaseStage;
@property(retain, nonatomic) NSURL *notifyURL; // @synthesize notifyURL=_notifyURL;
@property(retain, nonatomic) NSString *apiKey; // @synthesize apiKey=_apiKey;
- (void).cxx_destruct;
- (void)addBeforeNotifyHook:(CDUnknownBlockType)arg1;
- (void)addBeforeSendBlock:(CDUnknownBlockType)arg1;
- (void)setUser:(id)arg1 withName:(id)arg2 andEmail:(id)arg3;
- (_Bool)shouldSendReports;
- (id)init;

@end

