//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class CKAsyncTransaction, NSHashTable;

@interface CALayer (CKAsyncTransactionContainerTransactions)
- (void)ck_asyncTransactionContainerDidCompleteTransaction:(id)arg1;
- (void)ck_asyncTransactionContainerWillBeginTransaction:(id)arg1;

// Remaining properties
@property(retain, nonatomic, setter=ck_setAsyncLayerTransactions:) NSHashTable *ck_asyncLayerTransactions; // @dynamic ck_asyncLayerTransactions;
@property(retain, nonatomic, setter=ck_setCurrentAsyncLayerTransaction:) CKAsyncTransaction *ck_currentAsyncLayerTransaction; // @dynamic ck_currentAsyncLayerTransaction;
@end

