//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CKComponentDataSourceAttachController : NSObject
{
    NSMutableDictionary *_scopeIdentifierToAttachedViewMap;
}

- (void).cxx_destruct;
- (void)_detachComponentLayoutFromView:(id)arg1;
- (id)attachStateForScopeIdentifier:(int)arg1;
- (void)detachComponentLayoutWithScopeIdentifier:(int)arg1;
- (void)attachComponentLayout:(struct CKComponentLayout)arg1 withScopeIdentifier:(int)arg2 toView:(id)arg3;
- (void)dealloc;
- (id)init;

@end

