//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CKComponentDataSourceDelegate.h"
#import "UICollectionViewDataSource.h"

@class CKComponentDataSource, NSMapTable, NSString, UICollectionView;

@interface CKCollectionViewDataSource : NSObject <UICollectionViewDataSource, CKComponentDataSourceDelegate>
{
    CKComponentDataSource *_componentDataSource;
    CDUnknownFunctionPointerType _cellConfigurationFunction;
    NSMapTable *_cellToItemMap;
    UICollectionView *_collectionView;
    id <CKSupplementaryViewDataSource> _supplementaryViewDataSource;
}

+ (void)initialize;
@property(readonly, nonatomic) __weak id <CKSupplementaryViewDataSource> supplementaryViewDataSource; // @synthesize supplementaryViewDataSource=_supplementaryViewDataSource;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)componentDataSource:(id)arg1 didChangeSizeForObject:(id)arg2 atIndexPath:(id)arg3 animation:(const struct CKComponentBoundsAnimation *)arg4;
- (void)componentDataSource:(id)arg1 hasChangesOfTypes:(unsigned long long)arg2 changesetApplicator:(CDUnknownBlockType)arg3;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)announceDidDisappearForItemInCell:(id)arg1;
- (void)announceWillAppearForItemInCell:(id)arg1;
- (struct CGSize)sizeForItemAtIndexPath:(id)arg1;
- (id)modelForItemAtIndexPath:(id)arg1;
- (void)updateContextAndEnqueueReload:(id)arg1;
- (void)enqueueChangeset:(const struct Changeset *)arg1 constrainedSize:(const struct CKSizeRange *)arg2;
- (void)dealloc;
- (id)init;
- (id)initWithCollectionView:(id)arg1 supplementaryViewDataSource:(id)arg2 componentProvider:(Class)arg3 context:(id)arg4 cellConfigurationFunction:(CDUnknownFunctionPointerType)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

