//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CKTransactionalComponentDataSourceConfiguration : NSObject
{
    struct CKSizeRange _sizeRange;
    Class _componentProvider;
    id <NSObject> _context;
}

@property(readonly, nonatomic) id <NSObject> context; // @synthesize context=_context;
@property(readonly, nonatomic) Class componentProvider; // @synthesize componentProvider=_componentProvider;
- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (const struct CKSizeRange *)sizeRange;
- (id)initWithComponentProvider:(Class)arg1 context:(id)arg2 sizeRange:(const struct CKSizeRange *)arg3;

@end

