//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTEventEmitter.h"

@interface DCDBundleUpdaterManager : RCTEventEmitter
{
}

+ (id)__rct_export__501;
+ (id)__rct_export__400;
+ (void)load;
+ (id)moduleName;
- (void)reload;
- (void)getInitialBundleDownloaded:(CDUnknownBlockType)arg1 reject:(CDUnknownBlockType)arg2;
- (void)handleBundleDownloaded:(id)arg1;
- (id)supportedEvents;
- (void)stopObserving;
- (void)startObserving;
- (id)methodQueue;

@end

