//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SFSafariViewController.h"

@interface DCDWebViewController : SFSafariViewController
{
    long long _statusBarStyle;
}

@property(nonatomic) long long statusBarStyle; // @synthesize statusBarStyle=_statusBarStyle;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

@end

