//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface RCTImagePickerManager : NSObject <UIImagePickerControllerDelegate, UINavigationControllerDelegate, RCTBridgeModule>
{
    NSMutableArray *_pickers;
    NSMutableArray *_pickerCallbacks;
    NSMutableArray *_pickerCancelCallbacks;
    RCTBridge *_bridge;
}

+ (id)__rct_export__803;
+ (id)__rct_export__582;
+ (id)__rct_export__511;
+ (id)__rct_export__450;
+ (void)load;
+ (id)moduleName;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void).cxx_destruct;
- (void)_dismissPicker:(id)arg1 args:(id)arg2;
- (void)_presentPicker:(id)arg1 successCallback:(CDUnknownBlockType)arg2 cancelCallback:(CDUnknownBlockType)arg3;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)openSelectDialog:(id)arg1 successCallback:(CDUnknownBlockType)arg2 cancelCallback:(CDUnknownBlockType)arg3;
- (void)openCameraDialog:(id)arg1 successCallback:(CDUnknownBlockType)arg2 cancelCallback:(CDUnknownBlockType)arg3;
- (void)canUseCamera:(CDUnknownBlockType)arg1;
- (void)canRecordVideos:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

