//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTEventEmitter.h"

@interface RCTPushNotificationManager : RCTEventEmitter
{
    CDUnknownBlockType _requestPermissionsResolveBlock;
}

+ (id)__rct_export__35510;
+ (id)__rct_export__3379;
+ (id)__rct_export__3158;
+ (id)__rct_export__3107;
+ (id)__rct_export__3056;
+ (id)__rct_export__3005;
+ (id)__rct_export__2854;
+ (id)__rct_export__2803;
+ (id)__rct_export__2202;
+ (id)__rct_export__2131;
+ (id)__rct_export__2050;
+ (void)didReceiveLocalNotification:(id)arg1;
+ (void)didReceiveRemoteNotification:(id)arg1;
+ (void)didFailToRegisterForRemoteNotificationsWithError:(id)arg1;
+ (void)didRegisterForRemoteNotificationsWithDeviceToken:(id)arg1;
+ (void)didRegisterUserNotificationSettings:(id)arg1;
+ (void)load;
+ (id)moduleName;
- (void).cxx_destruct;
- (void)getScheduledLocalNotifications:(CDUnknownBlockType)arg1;
- (void)getInitialNotification:(CDUnknownBlockType)arg1 reject:(CDUnknownBlockType)arg2;
- (void)cancelLocalNotifications:(id)arg1;
- (void)cancelAllLocalNotifications;
- (void)scheduleLocalNotification:(id)arg1;
- (void)presentLocalNotification:(id)arg1;
- (void)checkPermissions:(CDUnknownBlockType)arg1;
- (void)abandonPermissions;
- (void)requestPermissions:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getApplicationIconBadgeNumber:(CDUnknownBlockType)arg1;
- (void)setApplicationIconBadgeNumber:(long long)arg1;
- (void)handleRegisterUserNotificationSettings:(id)arg1;
- (void)handleRemoteNotificationRegistrationError:(id)arg1;
- (void)handleRemoteNotificationsRegistered:(id)arg1;
- (void)handleRemoteNotificationReceived:(id)arg1;
- (void)handleLocalNotificationReceived:(id)arg1;
- (id)supportedEvents;
- (void)stopObserving;
- (void)startObserving;
- (id)methodQueue;

@end

