//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"
#import "UIDocumentInteractionControllerDelegate.h"

@class NSObject<OS_dispatch_queue>, NSString, RCTBridge, UIDocumentInteractionController;

@interface RNFetchBlob : NSObject <RCTBridgeModule, UIDocumentInteractionControllerDelegate>
{
    NSString *filePathPrefix;
    UIDocumentInteractionController *documentController;
    RCTBridge *_bridge;
}

+ (id)__rct_export__49830;
+ (id)__rct_export__49129;
+ (id)__rct_export__48028;
+ (id)__rct_export__47527;
+ (id)__rct_export__45626;
+ (id)__rct_export__43925;
+ (id)__rct_export__43324;
+ (id)__rct_export__42723;
+ (id)__rct_export__41622;
+ (id)__rct_export__40721;
+ (id)__rct_export__40420;
+ (id)__rct_export__38919;
+ (id)__rct_export__37518;
+ (id)__rct_export__36317;
+ (id)__rct_export__33816;
+ (id)__rct_export__30415;
+ (id)__rct_export__26514;
+ (id)__rct_export__24513;
+ (id)__rct_export__22912;
+ (id)__rct_export__21811;
+ (id)__rct_export__21110;
+ (id)__rct_export__2049;
+ (id)__rct_export__1908;
+ (id)__rct_export__1767;
+ (id)__rct_export__1736;
+ (id)__rct_export__1685;
+ (id)__rct_export__1614;
+ (id)__rct_export__1403;
+ (id)__rct_export__1122;
+ (id)__rct_export__1021;
+ (id)__rct_export__840;
+ (void)load;
+ (id)moduleName;
+ (id)getRCTBridge;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
@property(retain) UIDocumentInteractionController *documentController; // @synthesize documentController;
@property(retain, nonatomic) NSString *filePathPrefix; // @synthesize filePathPrefix;
- (void).cxx_destruct;
- (void)emitExpiredEvent:(CDUnknownBlockType)arg1;
- (void)getCookies:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (id)documentInteractionControllerViewControllerForPreview:(id)arg1;
- (void)df:(CDUnknownBlockType)arg1;
- (void)openDocument:(id)arg1 scheme:(id)arg2 resolver:(CDUnknownBlockType)arg3 rejecter:(CDUnknownBlockType)arg4;
- (void)previewDocument:(id)arg1 scheme:(id)arg2 resolver:(CDUnknownBlockType)arg3 rejecter:(CDUnknownBlockType)arg4;
- (void)slice:(id)arg1 dest:(id)arg2 start:(id)arg3 end:(id)arg4 resolver:(CDUnknownBlockType)arg5 rejecter:(CDUnknownBlockType)arg6;
- (void)enableUploadProgressReport:(id)arg1 interval:(id)arg2 count:(id)arg3;
- (void)enableProgressReport:(id)arg1 interval:(id)arg2 count:(id)arg3;
- (void)cancelRequest:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)getEnvironmentDirs:(CDUnknownBlockType)arg1;
- (void)readStream:(id)arg1 withEncoding:(id)arg2 bufferSize:(int)arg3 tick:(int)arg4 streamId:(id)arg5;
- (void)readFile:(id)arg1 encoding:(id)arg2 resolver:(CDUnknownBlockType)arg3 rejecter:(CDUnknownBlockType)arg4;
- (void)mkdir:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)mv:(id)arg1 toPath:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)cp:(id)arg1 toPath:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)lstat:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)stat:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)ls:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)removeSession:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)unlink:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)closeStream:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)writeChunk:(id)arg1 withData:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)writeArrayChunk:(id)arg1 withArray:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)writeStream:(id)arg1 withEncoding:(id)arg2 appendData:(_Bool)arg3 callback:(CDUnknownBlockType)arg4;
- (void)writeFileArray:(id)arg1 data:(id)arg2 append:(_Bool)arg3 resolver:(CDUnknownBlockType)arg4 rejecter:(CDUnknownBlockType)arg5;
- (void)writeFile:(id)arg1 encoding:(id)arg2 data:(id)arg3 append:(_Bool)arg4 resolver:(CDUnknownBlockType)arg5 rejecter:(CDUnknownBlockType)arg6;
- (void)exists:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)createFileASCII:(id)arg1 data:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)createFile:(id)arg1 data:(id)arg2 encoding:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)fetchBlob:(id)arg1 taskId:(id)arg2 method:(id)arg3 url:(id)arg4 headers:(id)arg5 body:(id)arg6 callback:(CDUnknownBlockType)arg7;
- (void)fetchBlobForm:(id)arg1 taskId:(id)arg2 method:(id)arg3 url:(id)arg4 headers:(id)arg5 form:(id)arg6 callback:(CDUnknownBlockType)arg7;
- (id)constantsToExport;
- (id)init;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

