//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BugsnagNotifier.h"

@interface BugsnagIosNotifier : BugsnagNotifier
{
}

- (void)dealloc;
- (void)lowMemoryWarning:(id)arg1;
- (void)orientationChanged:(id)arg1;
- (void)batteryChanged:(id)arg1;
- (void)start;

@end

