//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

#import "CKAsyncTransactionContainer.h"

@class CKAsyncTransaction;

@interface CALayer (CKAsyncTransactionContainer) <CKAsyncTransactionContainer>
@property(readonly, retain, nonatomic) CALayer *ck_parentTransactionContainer;
@property(readonly, retain, nonatomic) CKAsyncTransaction *ck_asyncTransaction;
- (void)ck_asyncTransactionContainerStateDidChange;
- (void)ck_cancelAsyncTransactions;
@property(readonly, nonatomic) unsigned long long ck_asyncTransactionContainerState;

// Remaining properties
@property(nonatomic, getter=ck_isAsyncTransactionContainer, setter=ck_setAsyncTransactionContainer:) _Bool ck_asyncTransactionContainer; // @dynamic ck_asyncTransactionContainer;
@end

