//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CKComponentStateListener.h"

@class CKComponentScopeRoot, NSSet, NSString, UIView;

@interface CKComponentLifecycleManager : NSObject <CKComponentStateListener>
{
    UIView *_mountedView;
    NSSet *_mountedComponents;
    Class _componentProvider;
    id <CKComponentSizeRangeProviding> _sizeRangeProvider;
    struct Mutex _mutex;
    CKComponentScopeRoot *_previousRoot;
    unordered_multimap_806dc048 _pendingStateUpdates;
    struct CKComponentLifecycleManagerState _state;
    id <CKComponentLifecycleManagerAsynchronousUpdateHandler> _asynchronousUpdateHandler;
    id <CKComponentLifecycleManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <CKComponentLifecycleManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <CKComponentLifecycleManagerAsynchronousUpdateHandler> asynchronousUpdateHandler; // @synthesize asynchronousUpdateHandler=_asynchronousUpdateHandler;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CKComponentLifecycleManagerState)state;
- (void)componentScopeHandleWithIdentifier:(int)arg1 rootIdentifier:(int)arg2 didReceiveStateUpdate:(CDUnknownBlockType)arg3 tryAsynchronousUpdate:(_Bool)arg4;
- (id)scopeRoot;
- (id)model;
- (struct CGSize)size;
- (_Bool)isAttachedToView;
- (void)detachFromView;
- (void)attachToView:(id)arg1;
- (void)_mountLayout;
- (void)updateWithStateWithoutMounting:(const struct CKComponentLifecycleManagerState *)arg1;
- (void)updateWithState:(const struct CKComponentLifecycleManagerState *)arg1;
- (struct CKComponentLayout)layoutForModel:(id)arg1 constrainedSize:(struct CKSizeRange)arg2 context:(id)arg3;
- (struct CKComponentLifecycleManagerState)prepareForUpdateWithModel:(id)arg1 constrainedSize:(struct CKSizeRange)arg2 context:(id)arg3;
- (void)dealloc;
- (id)initWithComponentProvider:(Class)arg1 sizeRangeProvider:(id)arg2;
- (id)initWithComponentProvider:(Class)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

