//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKComponentController;

@interface CKComponentScopeHandle : NSObject
{
    id <CKComponentStateListener> _listener;
    Class _componentClass;
    int _rootIdentifier;
    _Bool _acquired;
    int _globalIdentifier;
    CKComponentController *_controller;
    id _state;
}

+ (id)handleForComponent:(id)arg1;
@property(readonly, nonatomic) int globalIdentifier; // @synthesize globalIdentifier=_globalIdentifier;
@property(readonly, nonatomic) id state; // @synthesize state=_state;
@property(readonly, nonatomic) CKComponentController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (_Bool)acquireFromComponent:(id)arg1;
- (void)updateState:(CDUnknownBlockType)arg1 tryAsynchronousUpdate:(_Bool)arg2;
- (id)newHandleWithStateUpdates:(const unordered_multimap_806dc048 *)arg1;
- (id)initWithListener:(id)arg1 globalIdentifier:(int)arg2 rootIdentifier:(int)arg3 componentClass:(Class)arg4 state:(id)arg5 controller:(id)arg6;
- (id)initWithListener:(id)arg1 rootIdentifier:(int)arg2 componentClass:(Class)arg3 initialStateCreator:(CDUnknownBlockType)arg4;

@end

