//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"

@class NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface DCDBugsnagManager : NSObject <RCTBridgeModule>
{
}

+ (id)__rct_export__342;
+ (id)__rct_export__301;
+ (id)__rct_export__260;
+ (void)load;
+ (id)moduleName;
- (void)setMetadata:(id)arg1 metadata:(id)arg2;
- (void)clearUser;
- (void)setUser:(id)arg1;
- (id)initWithApiKey:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(readonly) Class superclass;

@end

