//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@interface DCDChatBodyComponent : CKCompositeComponent
{
}

+ (id)newWithMessage:(id)arg1 context:(id)arg2;
+ (id)contentComponent:(id)arg1 state:(id)arg2 context:(id)arg3;
- (void)handleTap:(id)arg1 context:(id)arg2;

@end

