//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@interface DCDChatComponent : CKCompositeComponent
{
}

+ (id)newWithModel:(id)arg1 context:(id)arg2;
+ (id)chatBodyComponent:(struct UIEdgeInsets)arg1 message:(id)arg2 context:(id)arg3;
+ (id)chatBodyWithHeadComponent:(struct UIEdgeInsets)arg1 message:(id)arg2 context:(id)arg3;
- (void)handleLongPress:(id)arg1 context:(id)arg2;

@end

