//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"

@class HNKCacheFormat, NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface DCDEmojiManager : NSObject <RCTBridgeModule>
{
    RCTBridge *_bridge;
    HNKCacheFormat *_hnk_cacheFormat;
}

+ (id)__rct_export__421;
+ (id)__rct_export__220;
+ (void)load;
+ (id)moduleName;
@property(retain, nonatomic) HNKCacheFormat *hnk_cacheFormat; // @synthesize hnk_cacheFormat=_hnk_cacheFormat;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void).cxx_destruct;
- (void)registerFormat:(id)arg1;
- (void)emojiFetched:(id)arg1;
- (void)fetchEmojiFromURL:(id)arg1 formatName:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(readonly) Class superclass;

@end

