//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SLKTextViewController.h"

#import "CKComponentDataSourceDelegate.h"
#import "CKComponentProvider.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CKComponentDataSource, NSArray, NSIndexPath, NSMutableSet, NSString, RCTEventDispatcher, UIColor;

@interface DCDMessageViewController : SLKTextViewController <CKComponentProvider, CKComponentDataSourceDelegate, UITableViewDataSource, UITableViewDelegate>
{
    _Bool _enabled;
    _Bool _rightButtonEnabled;
    _Bool _dark;
    _Bool _hasRows;
    _Bool _resetContentOffset;
    _Bool _scrollToAnimated;
    _Bool _isAtBottom;
    _Bool _isNearTop;
    _Bool _isLongPress;
    NSArray *_users;
    NSArray *_emojis;
    NSArray *_channels;
    NSMutableSet *_typingUsernames;
    double _bottomMarginToWindow;
    double _tableViewWidth;
    UIColor *_backgroundColor;
    RCTEventDispatcher *_eventDispatcher;
    CKComponentDataSource *_dataSource;
    CKComponentDataSource *_autoCompletionDataSource;
    NSIndexPath *_scrollToIndexPath;
    NSArray *_autoCompleteResults;
    NSMutableSet *_animateIndexPaths;
}

+ (id)componentForModel:(id)arg1 context:(id)arg2;
@property(retain, nonatomic) NSMutableSet *animateIndexPaths; // @synthesize animateIndexPaths=_animateIndexPaths;
@property(retain, nonatomic) NSArray *autoCompleteResults; // @synthesize autoCompleteResults=_autoCompleteResults;
@property(nonatomic) _Bool isLongPress; // @synthesize isLongPress=_isLongPress;
@property(nonatomic) _Bool isNearTop; // @synthesize isNearTop=_isNearTop;
@property(nonatomic) _Bool isAtBottom; // @synthesize isAtBottom=_isAtBottom;
@property(nonatomic) _Bool scrollToAnimated; // @synthesize scrollToAnimated=_scrollToAnimated;
@property(retain, nonatomic) NSIndexPath *scrollToIndexPath; // @synthesize scrollToIndexPath=_scrollToIndexPath;
@property(nonatomic) _Bool resetContentOffset; // @synthesize resetContentOffset=_resetContentOffset;
@property(nonatomic) _Bool hasRows; // @synthesize hasRows=_hasRows;
@property(retain, nonatomic) CKComponentDataSource *autoCompletionDataSource; // @synthesize autoCompletionDataSource=_autoCompletionDataSource;
@property(retain, nonatomic) CKComponentDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) RCTEventDispatcher *eventDispatcher; // @synthesize eventDispatcher=_eventDispatcher;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) _Bool dark; // @synthesize dark=_dark;
@property(nonatomic) _Bool rightButtonEnabled; // @synthesize rightButtonEnabled=_rightButtonEnabled;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) double tableViewWidth; // @synthesize tableViewWidth=_tableViewWidth;
@property(nonatomic) double bottomMarginToWindow; // @synthesize bottomMarginToWindow=_bottomMarginToWindow;
@property(retain, nonatomic) NSMutableSet *typingUsernames; // @synthesize typingUsernames=_typingUsernames;
@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
@property(retain, nonatomic) NSArray *emojis; // @synthesize emojis=_emojis;
@property(retain, nonatomic) NSArray *users; // @synthesize users=_users;
- (void).cxx_destruct;
- (_Bool)canPressRightButton;
- (double)slk_appropriateBottomMargin;
- (void)textViewDidChangeSelection:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)handleChatScroll;
- (void)scrollViewDidScroll:(id)arg1;
- (void)componentDataSource:(id)arg1 didChangeSizeForObject:(id)arg2 atIndexPath:(id)arg3 animation:(const struct CKComponentBoundsAnimation *)arg4;
- (void)componentDataSource:(id)arg1 hasChangesOfTypes:(unsigned long long)arg2 changesetApplicator:(CDUnknownBlockType)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)heightForAutoCompletionView;
- (void)updateAutoComplete:(id)arg1;
- (void)didChangeAutoCompletionPrefix:(id)arg1 andWord:(id)arg2;
- (void)forceLayout;
- (void)didCancelTextEditing:(id)arg1;
- (void)didCommitTextEditing:(id)arg1;
- (_Bool)canShowTypingIndicator;
- (void)didPasteMediaContent:(id)arg1;
- (void)fetchEmoji:(id)arg1;
- (void)didTapSeparator:(id)arg1;
- (void)didLongPressMessage:(id)arg1;
- (void)didTapLink:(id)arg1;
- (void)didTapMention:(id)arg1;
- (void)didTapChannel:(id)arg1;
- (void)didTapImage:(id)arg1;
- (void)didPressRightButton:(id)arg1;
- (void)didPressLeftButton:(id)arg1;
- (void)textDidUpdate:(_Bool)arg1;
- (void)scrollToNewMessages:(id)arg1 animated:(_Bool)arg2;
- (void)scrollToBottom:(_Bool)arg1;
- (void)updateRows:(id)arg1;
- (id)preprocessMessageRow:(id)arg1;
- (void)clearRows;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)reactTag;
- (void)handleLongPress:(id)arg1;
- (id)initWithEventDispatcher:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

