//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@interface DCDSeparatorComponent : CKCompositeComponent
{
}

+ (id)newWithText:(id)arg1 edgeInsets:(struct UIEdgeInsets)arg2 button:(id)arg3 color:(id)arg4 context:(id)arg5;
+ (id)newWithText:(id)arg1 button:(id)arg2 color:(id)arg3 context:(id)arg4;
- (void)handleTap:(id)arg1 context:(id)arg2;

@end

