//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNKCache.h"

@interface HNKCache (UIView)
+ (id)sharedFormatWithSize:(struct CGSize)arg1 scaleMode:(long long)arg2;
+ (void)registerSharedFormat:(id)arg1;
@end

