//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HNKThreadSafeMutableDictionary, NSDictionary, NSMutableDictionary, NSOperationQueue, NSString;

@interface HNKCache : NSObject
{
    NSMutableDictionary *_memoryCaches;
    NSMutableDictionary *_formats;
    NSString *_rootDirectory;
    NSOperationQueue *_operationQueue;
    HNKThreadSafeMutableDictionary *_fetcherConsolidatorDictionary;
}

+ (id)sharedCache;
@property(retain, nonatomic) HNKThreadSafeMutableDictionary *fetcherConsolidatorDictionary; // @synthesize fetcherConsolidatorDictionary=_fetcherConsolidatorDictionary;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(readonly, nonatomic) NSString *rootDirectory; // @synthesize rootDirectory=_rootDirectory;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)setDiskImage:(id)arg1 forKey:(id)arg2 format:(id)arg3;
- (void)enumeratePreloadImagesOfFormat:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)setMemoryImage:(id)arg1 forKey:(id)arg2 format:(id)arg3;
- (id)memoryImageForKey:(id)arg1 format:(id)arg2;
- (id)imageFromOriginal:(id)arg1 key:(id)arg2 format:(id)arg3;
- (void)fetchImageFromFetcher:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)removeImagesForKey:(id)arg1;
- (void)removeAllImagesForRegisteredFormats;
- (void)removeAllImages;
- (void)removeImagesOfFormatNamed:(id)arg1;
- (void)setImageInMemoryOnly:(id)arg1 forKey:(id)arg2 formatName:(id)arg3;
- (void)setImage:(id)arg1 forKey:(id)arg2 formatName:(id)arg3;
- (_Bool)fetchImageForKey:(id)arg1 formatName:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)cancelFetchForFetcher:(id)arg1 formatName:(id)arg2;
- (_Bool)fetchImageForFetcher:(id)arg1 formatName:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) NSDictionary *formats;
- (void)registerFormat:(id)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1;

@end

