//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HNKFetcherWrapper, NSMutableArray;

@interface HNKFetcherConsolidator : NSObject
{
    HNKFetcherWrapper *_primaryFetcher;
    NSMutableArray *_childFetchRequests;
    _Bool _cacheHit;
    _Bool _cancelled;
}

+ (id)uniqueKeyForFetcher:(id)arg1 formatName:(id)arg2;
@property(readonly, nonatomic) _Bool cancelled; // @synthesize cancelled=_cancelled;
@property(nonatomic) _Bool cacheHit; // @synthesize cacheHit=_cacheHit;
- (void).cxx_destruct;
- (void)dispatchFailureBlocksWithError:(id)arg1;
- (void)dispatchSuccessBlocksWithImage:(id)arg1;
- (void)removeFetchRequestWithFetcher:(id)arg1;
- (void)addFetchRequestWithFetcher:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (id)initWithFetcher:(id)arg1;

@end

