//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HNKFetcher.h"

@class NSDate, NSString, NSURL, NSURLSessionDataTask;

@interface HNKNetworkFetcher : NSObject <HNKFetcher>
{
    NSURL *_URL;
    _Bool _cancelled;
    NSURLSessionDataTask *_dataTask;
    NSDate *_startDate;
    NSDate *_finishDate;
    unsigned long long _dataLength;
}

@property(readonly, nonatomic) unsigned long long dataLength; // @synthesize dataLength=_dataLength;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;
- (void)failWithLocalizedDescription:(id)arg1 code:(long long)arg2 block:(CDUnknownBlockType)arg3;
- (void)dealloc;
@property(readonly, nonatomic) double duration;
- (void)cancelFetch;
- (void)fetchImageWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSString *key;
- (id)initWithURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

