//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (hnk_utils)
- (id)hnk_valueForExtendedFileAttribute:(id)arg1;
- (id)hnk_stringByEscapingFilename;
- (_Bool)hnk_setValue:(id)arg1 forExtendedFileAttribute:(id)arg2;
- (id)hnk_MD5String;
@end

