//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTConvert.h"

@interface RCTConvert (CoreLocation)
+ (CDStruct_c3b9c2ee)CLLocationCoordinate2D:(id)arg1;
+ (double)CLLocationDistance:(id)arg1;
+ (double)CLLocationDegrees:(id)arg1;
@end

