//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTConvert.h"

@interface RCTConvert (MapKit)
+ (id)RCTMapOverlayArray:(id)arg1;
+ (id)RCTMapOverlay:(id)arg1;
+ (id)RCTMapAnnotationArray:(id)arg1;
+ (id)RCTMapAnnotation:(id)arg1;
+ (unsigned long long)MKMapType:(id)arg1;
+ (CDStruct_90e2a262)MKCoordinateRegion:(id)arg1;
+ (CDStruct_c3b9c2ee)MKCoordinateSpan:(id)arg1;
@end

