//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTConvert.h"

@interface RCTConvert (ALAssetGroup)
+ (id)ALAssetsFilter:(id)arg1;
+ (unsigned long long)ALAssetsGroupType:(id)arg1;
@end

