//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTSRWebSocket.h"

@interface RCTSRWebSocket (React)
- (void)setReactTag:(id)arg1;
- (id)reactTag;
@end

