//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"

@class NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface RCTStatusBarManager : NSObject <RCTBridgeModule>
{
    RCTBridge *_bridge;
}

+ (id)__rct_export__1333;
+ (id)__rct_export__1222;
+ (id)__rct_export__1101;
+ (id)__rct_export__1020;
+ (void)load;
+ (id)moduleName;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void).cxx_destruct;
- (void)setNetworkActivityIndicatorVisible:(_Bool)arg1;
- (void)setHidden:(_Bool)arg1 withAnimation:(long long)arg2;
- (void)setStyle:(long long)arg1 animated:(_Bool)arg2;
- (void)getHeight:(CDUnknownBlockType)arg1;
- (void)applicationWillChangeStatusBarFrame:(id)arg1;
- (void)applicationDidChangeStatusBarFrame:(id)arg1;
- (void)emitEvent:(id)arg1 forNotification:(id)arg2;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
- (void)dealloc;
- (void)setBridge:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

