//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "RCTVideoPlayerViewControllerDelegate.h"

@class AVPlayer, AVPlayerItem, AVPlayerLayer, AVPlayerViewController, NSString, NSURL, RCTEventDispatcher, UIViewController;

@interface RCTVideo : UIView <RCTVideoPlayerViewControllerDelegate>
{
    AVPlayer *_player;
    AVPlayerItem *_playerItem;
    _Bool _playerItemObserversSet;
    _Bool _playerBufferEmpty;
    AVPlayerLayer *_playerLayer;
    AVPlayerViewController *_playerViewController;
    NSURL *_videoURL;
    RCTEventDispatcher *_eventDispatcher;
    _Bool _playbackRateObserverRegistered;
    _Bool _pendingSeek;
    float _pendingSeekTime;
    float _lastSeekTime;
    double _progressUpdateInterval;
    _Bool _controls;
    id _timeObserver;
    float _volume;
    float _rate;
    _Bool _muted;
    _Bool _paused;
    _Bool _repeat;
    _Bool _playbackStalled;
    NSString *_resizeMode;
    _Bool _fullscreenPlayerPresented;
    UIViewController *_presentingViewController;
}

- (void).cxx_destruct;
- (void)removeFromSuperview;
- (void)layoutSubviews;
- (void)removeReactSubview:(id)arg1;
- (void)insertReactSubview:(id)arg1 atIndex:(long long)arg2;
- (void)videoPlayerViewControllerDidDismiss:(id)arg1;
- (void)videoPlayerViewControllerWillDismiss:(id)arg1;
- (void)removePlayerLayer;
- (void)setControls:(_Bool)arg1;
- (void)usePlayerLayer;
- (void)usePlayerViewController;
- (void)setFullscreen:(_Bool)arg1;
- (_Bool)getFullscreen;
- (void)setRepeat:(_Bool)arg1;
- (void)applyModifiers;
- (void)setVolume:(float)arg1;
- (void)setMuted:(_Bool)arg1;
- (void)setRate:(float)arg1;
- (void)setSeek:(float)arg1;
- (void)setCurrentTime:(float)arg1;
- (float)getCurrentTime;
- (void)setPaused:(_Bool)arg1;
- (void)setResizeMode:(id)arg1;
- (void)playerItemDidReachEnd:(id)arg1;
- (void)playbackStalled:(id)arg1;
- (void)attachListeners;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)playerItemForSource:(id)arg1;
- (void)setSrc:(id)arg1;
- (void)removePlayerItemObservers;
- (void)addPlayerItemObservers;
- (id)calculatePlayableDuration;
- (void)sendProgressUpdate;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)dealloc;
- (void)removePlayerTimeObserver;
- (CDStruct_198678f7)playerItemDuration;
- (id)createPlayerViewController:(id)arg1 withPlayerItem:(id)arg2;
- (id)initWithEventDispatcher:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

