//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RTCAudioSession.h"

@interface RTCAudioSession (Configuration)
- (_Bool)setConfiguration:(id)arg1 active:(_Bool)arg2 shouldSetActive:(_Bool)arg3 error:(id *)arg4;
- (_Bool)setConfiguration:(id)arg1 active:(_Bool)arg2 error:(id *)arg3;
- (_Bool)setConfiguration:(id)arg1 error:(id *)arg2;
@end

