//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface RTCConfiguration : NSObject
{
    int _audioJitterBufferMaxPackets;
    int _iceConnectionReceivingTimeout;
    int _iceBackupCandidatePairPingInterval;
    NSArray *_iceServers;
    long long _iceTransportPolicy;
    long long _bundlePolicy;
    long long _rtcpMuxPolicy;
    long long _tcpCandidatePolicy;
    long long _continualGatheringPolicy;
    long long _keyType;
}

+ (id)stringForContinualGatheringPolicy:(long long)arg1;
+ (long long)continualGatheringPolicyForNativePolicy:(int)arg1;
+ (int)nativeContinualGatheringPolicyForPolicy:(long long)arg1;
+ (id)stringForTcpCandidatePolicy:(long long)arg1;
+ (long long)tcpCandidatePolicyForNativePolicy:(int)arg1;
+ (int)nativeEncryptionKeyTypeForKeyType:(long long)arg1;
+ (int)nativeTcpCandidatePolicyForPolicy:(long long)arg1;
+ (id)stringForRtcpMuxPolicy:(long long)arg1;
+ (long long)rtcpMuxPolicyForNativePolicy:(int)arg1;
+ (int)nativeRtcpMuxPolicyForPolicy:(long long)arg1;
+ (id)stringForBundlePolicy:(long long)arg1;
+ (long long)bundlePolicyForNativePolicy:(int)arg1;
+ (int)nativeBundlePolicyForPolicy:(long long)arg1;
+ (id)stringForTransportPolicy:(long long)arg1;
+ (long long)transportPolicyForTransportsType:(int)arg1;
+ (int)nativeTransportsTypeForTransportPolicy:(long long)arg1;
@property(nonatomic) long long keyType; // @synthesize keyType=_keyType;
@property(nonatomic) int iceBackupCandidatePairPingInterval; // @synthesize iceBackupCandidatePairPingInterval=_iceBackupCandidatePairPingInterval;
@property(nonatomic) int iceConnectionReceivingTimeout; // @synthesize iceConnectionReceivingTimeout=_iceConnectionReceivingTimeout;
@property(nonatomic) int audioJitterBufferMaxPackets; // @synthesize audioJitterBufferMaxPackets=_audioJitterBufferMaxPackets;
@property(nonatomic) long long continualGatheringPolicy; // @synthesize continualGatheringPolicy=_continualGatheringPolicy;
@property(nonatomic) long long tcpCandidatePolicy; // @synthesize tcpCandidatePolicy=_tcpCandidatePolicy;
@property(nonatomic) long long rtcpMuxPolicy; // @synthesize rtcpMuxPolicy=_rtcpMuxPolicy;
@property(nonatomic) long long bundlePolicy; // @synthesize bundlePolicy=_bundlePolicy;
@property(nonatomic) long long iceTransportPolicy; // @synthesize iceTransportPolicy=_iceTransportPolicy;
@property(copy, nonatomic) NSArray *iceServers; // @synthesize iceServers=_iceServers;
- (void).cxx_destruct;
- (struct RTCConfiguration *)createNativeConfiguration;
- (id)description;
- (id)init;

@end

