//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RTCPeerConnection.h"

@interface RTCPeerConnection (Stats)
- (void)statsForTrack:(id)arg1 statsOutputLevel:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
@end

