//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RTCRtpCodecParameters : NSObject
{
    int _payloadType;
    int _clockRate;
    int _channels;
    NSString *_mimeType;
}

@property(nonatomic) int channels; // @synthesize channels=_channels;
@property(nonatomic) int clockRate; // @synthesize clockRate=_clockRate;
@property(retain, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(nonatomic) int payloadType; // @synthesize payloadType=_payloadType;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct RtpCodecParameters nativeParameters;
- (id)initWithNativeParameters:(const struct RtpCodecParameters *)arg1;
- (id)init;

@end

