//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RTCRtpSender.h"

@class NSString, RTCMediaStreamTrack, RTCRtpParameters;

@interface RTCRtpSender : NSObject <RTCRtpSender>
{
    scoped_refptr_3635276f _nativeRtpSender;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithNativeRtpSender:(scoped_refptr_3635276f)arg1;
@property(readonly, nonatomic) scoped_refptr_3635276f nativeRtpSender;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
@property(copy, nonatomic) RTCMediaStreamTrack *track;
@property(copy, nonatomic) RTCRtpParameters *parameters;
@property(readonly, nonatomic) NSString *senderId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

