//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface RTCRtpParameters : NSObject
{
    NSArray *_encodings;
    NSArray *_codecs;
}

@property(copy, nonatomic) NSArray *codecs; // @synthesize codecs=_codecs;
@property(copy, nonatomic) NSArray *encodings; // @synthesize encodings=_encodings;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct RtpParameters nativeParameters;
- (id)initWithNativeParameters:(const struct RtpParameters *)arg1;
- (id)init;

@end

