//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface RTCStatsReport : NSObject
{
    double _timestamp;
    NSString *_type;
    NSString *_reportId;
    NSDictionary *_values;
}

@property(readonly, nonatomic) NSDictionary *values; // @synthesize values=_values;
@property(readonly, nonatomic) NSString *reportId; // @synthesize reportId=_reportId;
@property(readonly, nonatomic) NSString *type; // @synthesize type=_type;
@property(readonly, nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (id)initWithNativeReport:(const struct StatsReport *)arg1;
- (id)description;

@end

