//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface SLKInputAccessoryView : UIView
{
    UIView *_keyboardViewProxy;
}

@property(readonly, nonatomic) __weak UIView *keyboardViewProxy; // @synthesize keyboardViewProxy=_keyboardViewProxy;
- (void).cxx_destruct;
- (void)willMoveToSuperview:(id)arg1;

@end

