//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SLKTextView.h"

@interface SLKTextView (SLKAdditions)
+ (double)pointSizeDifferenceForCategory:(id)arg1;
- (void)slk_prepareForUndo:(id)arg1;
- (id)slk_wordAtRange:(struct _NSRange)arg1 rangeInText:(struct _NSRange *)arg2;
- (id)slk_wordAtCaretRange:(struct _NSRange *)arg1;
- (struct _NSRange)slk_insertText:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)slk_insertTextAtCaretRange:(id)arg1;
- (void)slk_insertNewLineBreak;
- (void)slk_scrollToBottomAnimated:(_Bool)arg1;
- (void)slk_scrollToCaretPositonAnimated:(_Bool)arg1;
- (void)slk_clearText:(_Bool)arg1;
@end

