//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSDictionary;

@interface UIImageInfoView : UIImageView
{
    NSDictionary *_INFO;
}

@property(retain, nonatomic) NSDictionary *INFO; // @synthesize INFO=_INFO;
- (void).cxx_destruct;
- (void)setupImageWithURL:(id)arg1;
- (void)registerFormat;

@end

