//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BugsnagMetaDataDelegate.h"

@class BugsnagConfiguration, BugsnagMetaData, NSDictionary, NSLock, NSString;

@interface BugsnagNotifier : NSObject <BugsnagMetaDataDelegate>
{
    BugsnagConfiguration *configuration;
    BugsnagMetaData *_state;
    NSDictionary *_details;
    NSLock *_metaDataLock;
}

@property(retain, nonatomic) NSLock *metaDataLock; // @synthesize metaDataLock=_metaDataLock;
@property(retain, nonatomic) NSDictionary *details; // @synthesize details=_details;
@property(retain, nonatomic) BugsnagMetaData *state; // @synthesize state=_state;
@property(retain, nonatomic) BugsnagConfiguration *configuration; // @synthesize configuration;
- (void).cxx_destruct;
- (void)serializeDictionary:(id)arg1 toJSON:(char **)arg2;
- (void)metaDataChanged:(id)arg1;
- (void)sendPendingReports;
- (void)notify:(id)arg1 withData:(id)arg2 atSeverity:(id)arg3 atDepth:(unsigned int)arg4;
- (void)start;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

