//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@interface CKLabelComponent : CKCompositeComponent
{
}

+ (id)newWithLabelAttributes:(const struct CKLabelAttributes *)arg1 viewAttributes:(const unordered_map_f50c1a1f *)arg2;

@end

