//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CKTextKitEntityAttribute : NSObject
{
    id <NSObject> _entity;
}

@property(readonly, nonatomic) id <NSObject> entity; // @synthesize entity=_entity;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)initWithEntity:(id)arg1;

@end

