//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor;

@interface CKTextKitShadower : NSObject
{
    struct UIEdgeInsets _calculatedShadowPadding;
    UIColor *_shadowColor;
    float _shadowOpacity;
    float _shadowRadius;
    struct CGSize _shadowOffset;
}

@property(readonly, nonatomic) float shadowRadius; // @synthesize shadowRadius=_shadowRadius;
@property(readonly, nonatomic) float shadowOpacity; // @synthesize shadowOpacity=_shadowOpacity;
@property(readonly, nonatomic) UIColor *shadowColor; // @synthesize shadowColor=_shadowColor;
@property(readonly, nonatomic) struct CGSize shadowOffset; // @synthesize shadowOffset=_shadowOffset;
- (void).cxx_destruct;
- (struct CGPoint)offsetPointWithExternalPoint:(struct CGPoint)arg1;
- (struct CGPoint)offsetPointWithInternalPoint:(struct CGPoint)arg1;
- (struct CGRect)offsetRectWithInternalRect:(struct CGRect)arg1;
- (struct CGRect)outsetRectWithInsetRect:(struct CGRect)arg1;
- (struct CGSize)outsetSizeWithInsetSize:(struct CGSize)arg1;
- (struct CGRect)insetRectWithConstrainedRect:(struct CGRect)arg1;
- (struct CGSize)insetSizeWithConstrainedSize:(struct CGSize)arg1;
- (struct UIEdgeInsets)shadowPadding;
- (void)setShadowInContext:(struct CGContext *)arg1;
- (BOOL)_shouldDrawShadow;
- (id)initWithShadowOffset:(struct CGSize)arg1 shadowColor:(id)arg2 shadowOpacity:(float)arg3 shadowRadius:(float)arg4;

@end

