//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKTextKitContext, CKTextKitShadower;

@interface CKTextKitRenderer : NSObject
{
    struct CGSize _calculatedSize;
    CKTextKitContext *_context;
    id <CKTextKitTruncating> _truncater;
    CKTextKitShadower *_shadower;
    struct CGSize _constrainedSize;
    struct CKTextKitAttributes _attributes;
}

@property(readonly, nonatomic) struct CGSize constrainedSize; // @synthesize constrainedSize=_constrainedSize;
@property(readonly, nonatomic) struct CKTextKitAttributes attributes; // @synthesize attributes=_attributes;
@property(readonly, nonatomic) CKTextKitShadower *shadower; // @synthesize shadower=_shadower;
@property(readonly, nonatomic) id <CKTextKitTruncating> truncater; // @synthesize truncater=_truncater;
@property(readonly, nonatomic) CKTextKitContext *context; // @synthesize context=_context;
- (id).cxx_construct;
- (void).cxx_destruct;
- (vector_d5f79a51)visibleRanges;
- (unsigned int)lineCount;
- (void)drawInContext:(struct CGContext *)arg1 bounds:(struct CGRect)arg2;
- (struct CGSize)size;
- (void)_calculateSize;
- (id)initWithTextKitAttributes:(const struct CKTextKitAttributes *)arg1 constrainedSize:(struct CGSize)arg2;
- (id)textCheckingResultAtPoint:(struct CGPoint)arg1;
- (struct CGRect)frameForTextRange:(struct _NSRange)arg1;
- (struct CGRect)trailingRect;
- (void)enumerateTextIndexesAtPosition:(struct CGPoint)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (struct CGRect)_internalRectForGlyphAtIndex:(unsigned int)arg1 measureOption:(unsigned int)arg2 layoutManager:(id)arg3 textContainer:(id)arg4 textStorage:(id)arg5;
- (unsigned int)nearestTextIndexAtPosition:(struct CGPoint)arg1;
- (id)rectsForTextRange:(struct _NSRange)arg1 measureOption:(unsigned int)arg2;

@end

