//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTViewManager.h"

@class RCTBridge;

@interface DCDAvatarManager : RCTViewManager
{
    RCTBridge *_bridge;
}

+ (id)__rct_export__430;
+ (id)propConfig_src;
+ (id)propConfig_format;
+ (void)load;
+ (id)moduleName;
- (id)bridge;
- (void).cxx_destruct;
- (void)registerFormat:(id)arg1 size:(id)arg2 rounded:(BOOL)arg3;
- (void)set_src:(id)arg1 forView:(id)arg2 withDefaultView:(id)arg3;
- (void)set_format:(id)arg1 forView:(id)arg2 withDefaultView:(id)arg3;
- (id)methodQueue;
- (id)view;

@end

