//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFHTTPRequestOperation, AFHTTPRequestOperationManager, NSDictionary, NSString;

@interface DCDBundleUpdater : NSObject
{
    id <DCDBundleUpdaterDelegate> _delegate;
    NSDictionary *_launchOptions;
    NSString *_URLString;
    AFHTTPRequestOperationManager *_manager;
    AFHTTPRequestOperation *_currentOperation;
}

@property(retain, nonatomic) AFHTTPRequestOperation *currentOperation; // @synthesize currentOperation=_currentOperation;
@property(retain, nonatomic) AFHTTPRequestOperationManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) NSString *URLString; // @synthesize URLString=_URLString;
@property(retain, nonatomic) NSDictionary *launchOptions; // @synthesize launchOptions=_launchOptions;
@property(nonatomic) __weak id <DCDBundleUpdaterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)cacheBundleURL;
- (id)mainBundleURL;
- (id)bundleURL;
- (id)checksumForData:(id)arg1;
- (id)checksum;
- (void)downloadUpdate;
- (void)checkForUpdate;
- (id)initWithURLString:(id)arg1 launchOptions:(id)arg2;

@end

