//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SLKTextViewController.h"

#import "CKComponentDataSourceDelegate.h"
#import "CKComponentProvider.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CKComponentDataSource, NSArray, NSIndexPath, NSMutableSet, NSString, RCTEventDispatcher, UIColor;

@interface DCDMessageViewController : SLKTextViewController <CKComponentProvider, CKComponentDataSourceDelegate, UITableViewDataSource, UITableViewDelegate>
{
    BOOL _enabled;
    BOOL _rightButtonEnabled;
    BOOL _dark;
    BOOL _hasRows;
    BOOL _resetContentOffset;
    BOOL _scrollToAnimated;
    BOOL _isAtBottom;
    BOOL _isNearTop;
    BOOL _isLongPress;
    BOOL _sendNextScroll;
    BOOL _canAutoComplete;
    NSArray *_users;
    NSArray *_emojis;
    NSArray *_channels;
    NSMutableSet *_typingUsernames;
    float _bottomMarginToWindow;
    float _tableViewWidth;
    UIColor *_backgroundColor;
    RCTEventDispatcher *_eventDispatcher;
    CKComponentDataSource *_dataSource;
    CKComponentDataSource *_autoCompletionDataSource;
    NSIndexPath *_scrollToIndexPath;
    NSArray *_autoCompleteResults;
    NSMutableSet *_animateIndexPaths;
}

+ (id)componentForModel:(id)arg1 context:(id)arg2;
@property(nonatomic) BOOL canAutoComplete; // @synthesize canAutoComplete=_canAutoComplete;
@property(retain, nonatomic) NSMutableSet *animateIndexPaths; // @synthesize animateIndexPaths=_animateIndexPaths;
@property(nonatomic) BOOL sendNextScroll; // @synthesize sendNextScroll=_sendNextScroll;
@property(retain, nonatomic) NSArray *autoCompleteResults; // @synthesize autoCompleteResults=_autoCompleteResults;
@property(nonatomic) BOOL isLongPress; // @synthesize isLongPress=_isLongPress;
@property(nonatomic) BOOL isNearTop; // @synthesize isNearTop=_isNearTop;
@property(nonatomic) BOOL isAtBottom; // @synthesize isAtBottom=_isAtBottom;
@property(nonatomic) BOOL scrollToAnimated; // @synthesize scrollToAnimated=_scrollToAnimated;
@property(retain, nonatomic) NSIndexPath *scrollToIndexPath; // @synthesize scrollToIndexPath=_scrollToIndexPath;
@property(nonatomic) BOOL resetContentOffset; // @synthesize resetContentOffset=_resetContentOffset;
@property(nonatomic) BOOL hasRows; // @synthesize hasRows=_hasRows;
@property(retain, nonatomic) CKComponentDataSource *autoCompletionDataSource; // @synthesize autoCompletionDataSource=_autoCompletionDataSource;
@property(retain, nonatomic) CKComponentDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) RCTEventDispatcher *eventDispatcher; // @synthesize eventDispatcher=_eventDispatcher;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) BOOL dark; // @synthesize dark=_dark;
@property(nonatomic) BOOL rightButtonEnabled; // @synthesize rightButtonEnabled=_rightButtonEnabled;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
@property(nonatomic) float tableViewWidth; // @synthesize tableViewWidth=_tableViewWidth;
@property(nonatomic) float bottomMarginToWindow; // @synthesize bottomMarginToWindow=_bottomMarginToWindow;
@property(retain, nonatomic) NSMutableSet *typingUsernames; // @synthesize typingUsernames=_typingUsernames;
@property(retain, nonatomic) NSArray *channels; // @synthesize channels=_channels;
@property(retain, nonatomic) NSArray *emojis; // @synthesize emojis=_emojis;
@property(retain, nonatomic) NSArray *users; // @synthesize users=_users;
- (void).cxx_destruct;
- (void)sendScrollEventWithType:(int)arg1 scrollView:(id)arg2;
- (BOOL)canPressRightButton;
- (float)slk_appropriateBottomMargin;
- (void)textViewDidChangeSelection:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)handleChatScroll;
- (void)scrollViewDidScroll:(id)arg1;
- (void)componentDataSource:(id)arg1 didChangeSizeForObject:(id)arg2 atIndexPath:(id)arg3 animation:(const struct CKComponentBoundsAnimation *)arg4;
- (void)componentDataSource:(id)arg1 hasChangesOfTypes:(unsigned int)arg2 changesetApplicator:(CDUnknownBlockType)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)heightForAutoCompletionView;
- (void)updateAutoComplete:(id)arg1;
- (void)didChangeAutoCompletionPrefix:(id)arg1 andWord:(id)arg2;
- (void)forceLayout;
- (void)didCancelTextEditing:(id)arg1;
- (void)didCommitTextEditing:(id)arg1;
- (BOOL)canShowTypingIndicator;
- (void)didPasteMediaContent:(id)arg1;
- (void)fetchEmoji:(id)arg1;
- (void)didTapSeparator:(id)arg1;
- (void)didLongPressMessage:(id)arg1;
- (void)didTapMention:(id)arg1;
- (void)didTapChannel:(id)arg1;
- (void)didTapImage:(id)arg1;
- (void)didPressRightButton:(id)arg1;
- (void)didPressLeftButton:(id)arg1;
- (void)textDidUpdate:(BOOL)arg1;
- (void)didHideKeyboard:(id)arg1;
- (void)didShowKeyboard:(id)arg1;
- (void)scrollToNewMessages:(id)arg1 animated:(BOOL)arg2;
- (void)scrollToBottom:(BOOL)arg1;
- (void)updateRows:(id)arg1;
- (id)preprocessMessageRow:(id)arg1;
- (void)clearRows;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)reactTag;
- (void)handleLongPress:(id)arg1;
- (id)initWithEventDispatcher:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

