//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"
#import "RCTInvalidating.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface DCDTimer : NSObject <RCTBridgeModule, RCTInvalidating>
{
    RCTBridge *_bridge;
    NSMutableDictionary *_timers;
}

+ (id)__rct_export__571;
+ (id)__rct_export__470;
+ (void)load;
+ (id)moduleName;
@property(retain, nonatomic) NSMutableDictionary *timers; // @synthesize timers=_timers;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void).cxx_destruct;
- (void)tick:(id)arg1;
- (void)clearInterval:(id)arg1;
- (void)setInterval:(id)arg1 delay:(id)arg2;
- (void)invalidate;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

