//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"
#import "RCTInvalidating.h"

@class NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface DCDVoiceEngine : NSObject <RCTBridgeModule, RCTInvalidating>
{
    BOOL _shouldForwardVADLevelEventsToJavaScript;
    struct Discord *_discord;
    RCTBridge *_bridge;
}

+ (id)__rct_export__44424;
+ (id)__rct_export__44023;
+ (id)__rct_export__43622;
+ (id)__rct_export__43221;
+ (id)__rct_export__42620;
+ (id)__rct_export__42219;
+ (id)__rct_export__41618;
+ (id)__rct_export__41217;
+ (id)__rct_export__39516;
+ (id)__rct_export__39115;
+ (id)__rct_export__33314;
+ (id)__rct_export__32913;
+ (id)__rct_export__32512;
+ (id)__rct_export__32111;
+ (id)__rct_export__31710;
+ (id)__rct_export__3139;
+ (id)__rct_export__3098;
+ (id)__rct_export__3047;
+ (id)__rct_export__2996;
+ (id)__rct_export__2945;
+ (id)__rct_export__2684;
+ (id)__rct_export__2583;
+ (id)__rct_export__1712;
+ (id)__rct_export__1661;
+ (id)__rct_export__1470;
+ (id)convertDeviceDescriptions:(const vector_868a1150 *)arg1;
+ (void)load;
+ (id)moduleName;
@property BOOL shouldForwardVADLevelEventsToJavaScript; // @synthesize shouldForwardVADLevelEventsToJavaScript=_shouldForwardVADLevelEventsToJavaScript;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
@property struct Discord *discord; // @synthesize discord=_discord;
- (void).cxx_destruct;
- (unsigned long long)convertString:(id)arg1;
- (void)debugDump:(CDUnknownBlockType)arg1;
- (void)setKeepAliveChannel:(BOOL)arg1;
- (void)setPTTActive:(BOOL)arg1;
- (void)setOutputDevice:(int)arg1;
- (void)getOutputDevices:(CDUnknownBlockType)arg1;
- (void)setInputDevice:(int)arg1;
- (void)getInputDevices:(CDUnknownBlockType)arg1;
- (void)playSound:(id)arg1 volume:(float)arg2;
- (void)setEmitPTTScanCodes:(BOOL)arg1;
- (void)setEmitVADLevel:(BOOL)arg1;
- (void)setInputMode:(int)arg1 options:(id)arg2;
- (void)setDuckingPreference:(BOOL)arg1;
- (void)setAttenuationMode:(BOOL)arg1 factor:(float)arg2;
- (void)setOutputVolume:(float)arg1;
- (void)setInputVolume:(float)arg1;
- (void)setSelfDeafen:(BOOL)arg1;
- (void)setSelfMute:(BOOL)arg1;
- (void)setLocalMute:(id)arg1 isMuted:(BOOL)arg2;
- (void)setLocalVolume:(id)arg1 scaling:(float)arg2;
- (void)destroyUser:(id)arg1;
- (void)mergeUsers:(id)arg1;
- (void)getEncryptionModes:(CDUnknownBlockType)arg1;
- (void)setTransportOptions:(id)arg1;
- (void)destroyTransport;
- (void)createTransport:(unsigned int)arg1 userId:(id)arg2 serverIp:(id)arg3 port:(int)arg4 callback:(CDUnknownBlockType)arg5;
- (void)handleDeviceChangedChanged:(id)arg1;
- (void)handleVoiceLevelChanged:(id)arg1;
- (void)handlePTTSystemInputEvent:(id)arg1;
- (void)handleSpeakingStatusChanged:(id)arg1;
- (void)invalidate;
- (BOOL)isValid;
- (id)constantsToExport;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(readonly) Class superclass;

@end

