//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HNKFetcher.h"

@class NSString;

@interface HNKFetcherWrapper : NSObject <HNKFetcher>
{
    id <HNKFetcher> _fetcher;
}

- (void).cxx_destruct;
- (void)cancelFetch;
- (void)fetchImageWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSString *key;
- (id)initWithFetcher:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

