//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSThread;

@interface KSCrashDeadlockMonitor : NSObject
{
    BOOL _awaitingResponse;
    NSThread *_monitorThread;
    unsigned int _mainThread;
}

@property BOOL awaitingResponse; // @synthesize awaitingResponse=_awaitingResponse;
@property(nonatomic) unsigned int mainThread; // @synthesize mainThread=_mainThread;
@property(retain, nonatomic) NSThread *monitorThread; // @synthesize monitorThread=_monitorThread;
- (void).cxx_destruct;
- (void)runMonitor;
- (void)handleDeadlock;
- (void)watchdogAnswer;
- (void)watchdogPulse;
- (void)cancel;
- (void)dealloc;
- (id)init;

@end

