//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class KSCrashReportStore, NSArray, NSDictionary, NSString;

@interface KSCrash : NSObject
{
    _Bool _printTraceToStdout;
    _Bool _searchThreadNames;
    _Bool _searchQueueNames;
    _Bool _introspectMemory;
    _Bool _suspendThreadsForUserReported;
    id <KSCrashReportFilter> _sink;
    NSDictionary *_userInfo;
    int _deleteBehaviorAfterSendAll;
    int _handlingCrashTypes;
    unsigned long _zombieCacheSize;
    CDUnknownFunctionPointerType _onCrash;
    KSCrashReportStore *_crashReportStore;
    NSString *_bundleName;
    NSString *_logFilePath;
    NSString *_nextCrashID;
    NSArray *_doNotIntrospectClasses;
    double _deadlockWatchdogInterval;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(nonatomic) _Bool suspendThreadsForUserReported; // @synthesize suspendThreadsForUserReported=_suspendThreadsForUserReported;
@property(retain, nonatomic) NSArray *doNotIntrospectClasses; // @synthesize doNotIntrospectClasses=_doNotIntrospectClasses;
@property(nonatomic) _Bool introspectMemory; // @synthesize introspectMemory=_introspectMemory;
@property(nonatomic) _Bool searchQueueNames; // @synthesize searchQueueNames=_searchQueueNames;
@property(nonatomic) _Bool searchThreadNames; // @synthesize searchThreadNames=_searchThreadNames;
@property(retain, nonatomic) NSString *nextCrashID; // @synthesize nextCrashID=_nextCrashID;
@property(retain, nonatomic) NSString *logFilePath; // @synthesize logFilePath=_logFilePath;
@property(retain, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
@property(retain, nonatomic) KSCrashReportStore *crashReportStore; // @synthesize crashReportStore=_crashReportStore;
@property(nonatomic) CDUnknownFunctionPointerType onCrash; // @synthesize onCrash=_onCrash;
@property(nonatomic) _Bool printTraceToStdout; // @synthesize printTraceToStdout=_printTraceToStdout;
@property(nonatomic) double deadlockWatchdogInterval; // @synthesize deadlockWatchdogInterval=_deadlockWatchdogInterval;
@property(nonatomic) unsigned long zombieCacheSize; // @synthesize zombieCacheSize=_zombieCacheSize;
@property(nonatomic) int handlingCrashTypes; // @synthesize handlingCrashTypes=_handlingCrashTypes;
@property(nonatomic) int deleteBehaviorAfterSendAll; // @synthesize deleteBehaviorAfterSendAll=_deleteBehaviorAfterSendAll;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) id <KSCrashReportFilter> sink; // @synthesize sink=_sink;
- (void).cxx_destruct;
- (void)applicationWillTerminate;
- (void)applicationWillEnterForeground;
- (void)applicationDidEnterBackground;
- (void)applicationWillResignActive;
- (void)applicationDidBecomeActive;
- (id)nullTerminated:(id)arg1;
- (id)generateUUIDString;
- (BOOL)ensureDirectoryExists:(id)arg1;
- (BOOL)redirectConsoleLogsToDefaultFile;
- (BOOL)redirectConsoleLogsToFile:(id)arg1 overwrite:(BOOL)arg2;
- (id)allReports;
- (void)sendReports:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;
- (id)crashReportsPath;
- (unsigned int)reportCount;
- (BOOL)crashedLastLaunch;
- (int)sessionsSinceLaunch;
- (double)backgroundDurationSinceLaunch;
- (double)activeDurationSinceLaunch;
- (int)sessionsSinceLastCrash;
- (int)launchesSinceLastCrash;
- (double)backgroundDurationSinceLastCrash;
- (double)activeDurationSinceLastCrash;
- (void)reportUserException:(id)arg1 reason:(id)arg2 lineOfCode:(id)arg3 stackTrace:(id)arg4 terminateProgram:(BOOL)arg5;
- (void)deleteAllReports;
- (void)sendAllReportsWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)install;
@property(readonly, retain, nonatomic) NSString *stateFilePath;
@property(readonly, retain, nonatomic) NSString *recrashReportPath;
@property(readonly, retain, nonatomic) NSString *crashReportPath;
- (void)dealloc;
- (id)init;

@end

