//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (MASAdditions)
- (id)mas_commonSuperviewOfViews;
- (void)mas_distributeViewsAlongAxis:(unsigned int)arg1 withFixedItemLength:(float)arg2 leadSpacing:(float)arg3 tailSpacing:(float)arg4;
- (void)mas_distributeViewsAlongAxis:(unsigned int)arg1 withFixedSpacing:(float)arg2 leadSpacing:(float)arg3 tailSpacing:(float)arg4;
- (id)mas_remakeConstraints:(CDUnknownBlockType)arg1;
- (id)mas_updateConstraints:(CDUnknownBlockType)arg1;
- (id)mas_makeConstraints:(CDUnknownBlockType)arg1;
@end

