//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (StdString)
+ (id)stringForStdString:(const basic_string_7d00a7a9 *)arg1;
+ (basic_string_7d00a7a9)stdStringForString:(id)arg1;
@property(readonly, nonatomic) basic_string_7d00a7a9 stdString;
@end

