//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTBridge.h"

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, RCTDisplayLink;

@interface RCTBatchedBridge : RCTBridge
{
    BOOL _loading;
    BOOL _valid;
    BOOL _wasBatchActive;
    id <RCTJavaScriptExecutor> _javaScriptExecutor;
    NSMutableArray *_pendingCalls;
    NSMutableDictionary *_moduleDataByName;
    NSArray *_moduleDataByID;
    NSDictionary *_modulesByName_DEPRECATED;
    NSArray *_moduleClassesByID;
    RCTDisplayLink *_jsDisplayLink;
    NSMutableSet *_frameUpdateObservers;
    unsigned int _syncInitializedModules;
    unsigned int _asyncInitializedModules;
    RCTBridge *_parentBridge;
}

@property(nonatomic) __weak RCTBridge *parentBridge; // @synthesize parentBridge=_parentBridge;
- (void).cxx_destruct;
- (BOOL)isBatchActive;
- (void)stopProfiling:(CDUnknownBlockType)arg1;
- (void)startProfiling;
- (void)_jsThreadUpdate:(id)arg1;
- (BOOL)_handleRequestNumber:(unsigned int)arg1 moduleID:(unsigned int)arg2 methodID:(unsigned int)arg3 params:(id)arg4;
- (void)batchDidComplete;
- (void)partialBatchDidFlush;
- (void)handleBuffer:(id)arg1;
- (void)handleBuffer:(id)arg1 batchEnded:(BOOL)arg2;
- (void)_actuallyInvokeCallback:(id)arg1 arguments:(id)arg2;
- (void)_actuallyInvokeAndProcessModule:(id)arg1 method:(id)arg2 arguments:(id)arg3;
- (void)enqueueApplicationScript:(id)arg1 url:(id)arg2 onComplete:(CDUnknownBlockType)arg3;
- (void)_immediatelyCallTimer:(id)arg1;
- (void)enqueueCallback:(id)arg1 args:(id)arg2;
- (void)enqueueJSCall:(id)arg1 args:(id)arg2;
- (void)logMessage:(id)arg1 level:(id)arg2;
- (void)invalidate;
- (void)dispatchBlock:(CDUnknownBlockType)arg1 queue:(id)arg2;
- (BOOL)isValid;
- (BOOL)isLoading;
- (id)delegate;
- (void)setBundleURL:(id)arg1;
- (id)bundleURL;
- (void)setExecutorClass:(Class)arg1;
- (Class)executorClass;
- (void)reload;
- (void)bindKeys;
- (void)setUp;
- (id)initWithBundleURL:(id)arg1 moduleProvider:(CDUnknownBlockType)arg2 launchOptions:(id)arg3;
- (void)stopLoadingWithError:(id)arg1;
- (void)didFinishLoading;
- (void)executeSourceCode:(id)arg1;
- (void)injectJSONConfiguration:(id)arg1 onComplete:(CDUnknownBlockType)arg2;
- (void)updateJSDisplayLinkState;
- (id)moduleConfig;
- (void)registerModuleForFrameUpdates:(id)arg1 withModuleData:(id)arg2;
- (void)setUpExecutor;
- (void)initModules;
- (id)configForModuleName:(id)arg1;
- (id)moduleForName:(id)arg1;
- (id)moduleClasses;
- (void)loadSource:(CDUnknownBlockType)arg1;
- (void)start;
- (id)initWithParentBridge:(id)arg1;
- (id)modules;

@end

