//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTJavaScriptExecutor.h"

@class NSObject<OS_dispatch_queue>, NSString, NSThread, NSURL, RCTBridge, RCTJavaScriptContext;

@interface RCTJSCExecutor : NSObject <RCTJavaScriptExecutor>
{
    RCTJavaScriptContext *_context;
    NSThread *_javaScriptThread;
    NSURL *_bundleURL;
    BOOL _valid;
    RCTBridge *_bridge;
}

+ (id)__rct_export__5901;
+ (void)runRunLoopThread;
+ (void)load;
+ (id)moduleName;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
@property(readonly, nonatomic, getter=isValid) BOOL valid; // @synthesize valid=_valid;
- (void).cxx_destruct;
- (void)setContextName:(id)arg1;
- (void)injectJSONText:(id)arg1 asGlobalObjectNamed:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)_runBlock:(CDUnknownBlockType)arg1;
- (void)executeAsyncBlockOnJavaScriptQueue:(CDUnknownBlockType)arg1;
- (void)executeBlockOnJavaScriptQueue:(CDUnknownBlockType)arg1;
- (void)executeApplicationScript:(id)arg1 sourceURL:(id)arg2 onComplete:(CDUnknownBlockType)arg3;
- (void)_executeJSCall:(id)arg1 arguments:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)invokeCallbackID:(id)arg1 arguments:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)callFunctionOnModule:(id)arg1 method:(id)arg2 arguments:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)flushedQueue:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)invalidate;
- (void)toggleProfilingFlag:(id)arg1;
- (void)setUp;
- (void)addSynchronousHookWithName:(id)arg1 usingBlock:(id)arg2;
- (id)context;
- (id)initWithJavaScriptThread:(id)arg1 globalContextRef:(struct OpaqueJSContext *)arg2;
- (id)initWithJavaScriptThread:(id)arg1 context:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(readonly) Class superclass;

@end

