//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"

@class NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface RCTPushNotificationManager : NSObject <RCTBridgeModule>
{
    RCTBridge *_bridge;
}

+ (id)__rct_export__2207;
+ (id)__rct_export__2156;
+ (id)__rct_export__2105;
+ (id)__rct_export__1814;
+ (id)__rct_export__1763;
+ (id)__rct_export__1242;
+ (id)__rct_export__1171;
+ (id)__rct_export__1090;
+ (void)didReceiveRemoteNotification:(id)arg1;
+ (void)didRegisterForRemoteNotificationsWithDeviceToken:(id)arg1;
+ (void)didRegisterUserNotificationSettings:(id)arg1;
+ (void)load;
+ (id)moduleName;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void).cxx_destruct;
- (void)cancelAllLocalNotifications;
- (void)scheduleLocalNotification:(id)arg1;
- (void)presentLocalNotification:(id)arg1;
- (void)checkPermissions:(CDUnknownBlockType)arg1;
- (void)abandonPermissions;
- (void)requestPermissions:(id)arg1;
- (void)getApplicationIconBadgeNumber:(CDUnknownBlockType)arg1;
- (void)setApplicationIconBadgeNumber:(int)arg1;
- (void)handleRemoteNotificationsRegistered:(id)arg1;
- (void)handleRemoteNotificationReceived:(id)arg1;
- (id)constantsToExport;
- (void)setBridge:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(readonly) Class superclass;

@end

