//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"
#import "RCTInvalidating.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString, RCTBridge, RCTLayoutAnimation;

@interface RCTUIManager : NSObject <RCTBridgeModule, RCTInvalidating>
{
    NSObject<OS_dispatch_queue> *_shadowQueue;
    NSMutableSet *_rootViewTags;
    NSMutableArray *_pendingUIBlocks;
    RCTLayoutAnimation *_nextLayoutAnimation;
    RCTLayoutAnimation *_layoutAnimation;
    NSMutableDictionary *_shadowViewRegistry;
    NSMutableDictionary *_viewRegistry;
    NSDictionary *_componentDataByName;
    NSMutableSet *_bridgeTransactionListeners;
    BOOL _unsafeFlushUIChangesBeforeBatchEnds;
    BOOL _invalidateLayoutChange;
    RCTBridge *_bridge;
}

+ (id)JSResponder;
+ (id)__rct_export__128216;
+ (id)__rct_export__120215;
+ (id)__rct_export__119214;
+ (id)__rct_export__114413;
+ (id)__rct_export__112812;
+ (id)__rct_export__111211;
+ (id)__rct_export__104010;
+ (id)__rct_export__9179;
+ (id)__rct_export__9098;
+ (id)__rct_export__8997;
+ (id)__rct_export__8876;
+ (id)__rct_export__8515;
+ (id)__rct_export__7834;
+ (id)__rct_export__7523;
+ (id)__rct_export__7312;
+ (id)__rct_export__7081;
+ (id)__rct_export__6500;
+ (void)load;
+ (id)moduleName;
@property(nonatomic) BOOL invalidateLayoutChange; // @synthesize invalidateLayoutChange=_invalidateLayoutChange;
@property BOOL unsafeFlushUIChangesBeforeBatchEnds; // @synthesize unsafeFlushUIChangesBeforeBatchEnds=_unsafeFlushUIChangesBeforeBatchEnds;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void).cxx_destruct;
- (void)configureNextLayoutAnimation:(id)arg1 withCallback:(CDUnknownBlockType)arg2 errorCallback:(CDUnknownBlockType)arg3;
- (id)constantsToExport;
- (void)clearJSResponder;
- (void)setJSResponder:(id)arg1 blockNativeResponder:(BOOL)arg2;
- (void)measureViewsInRect:(struct CGRect)arg1 parentView:(id)arg2 errorCallback:(CDUnknownBlockType)arg3 callback:(CDUnknownBlockType)arg4;
- (void)measureLayoutRelativeToParent:(id)arg1 errorCallback:(CDUnknownBlockType)arg2 callback:(CDUnknownBlockType)arg3;
- (void)measureLayout:(id)arg1 relativeTo:(id)arg2 errorCallback:(CDUnknownBlockType)arg3 callback:(CDUnknownBlockType)arg4;
- (void)measure:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)setNeedsLayout;
- (void)flushUIBlocks;
- (void)_layoutAndMount;
- (void)batchDidComplete;
- (void)partialBatchDidFlush;
- (void)findSubviewIn:(id)arg1 atPoint:(struct CGPoint)arg2 callback:(CDUnknownBlockType)arg3;
- (void)blur:(id)arg1;
- (void)focus:(id)arg1;
- (void)updateView:(id)arg1 viewName:(id)arg2 props:(id)arg3;
- (void)createView:(id)arg1 viewName:(id)arg2 rootTag:(id)arg3 props:(id)arg4;
- (void)_manageChildren:(id)arg1 moveFromIndices:(id)arg2 moveToIndices:(id)arg3 addChildReactTags:(id)arg4 addAtIndices:(id)arg5 removeAtIndices:(id)arg6 registry:(id)arg7;
- (void)manageChildren:(id)arg1 moveFromIndices:(id)arg2 moveToIndices:(id)arg3 addChildReactTags:(id)arg4 addAtIndices:(id)arg5 removeAtIndices:(id)arg6;
- (void)setChildren:(id)arg1 reactTags:(id)arg2;
- (void)replaceExistingNonRootView:(id)arg1 withView:(id)arg2;
- (void)removeRootView:(id)arg1;
- (void)_removeChildren:(id)arg1 fromContainer:(id)arg2;
- (id)_childrenToRemoveFromContainer:(id)arg1 atIndices:(id)arg2;
- (void)removeSubviewsFromContainerWithID:(id)arg1;
- (void)_amendPendingUIBlocksWithStylePropagationUpdateForRootView:(id)arg1;
- (CDUnknownBlockType)uiBlockWithLayoutUpdateForRootView:(id)arg1;
- (void)addUIBlock:(CDUnknownBlockType)arg1;
- (void)_purgeChildren:(id)arg1 fromRegistry:(id)arg2;
- (void)setBackgroundColor:(id)arg1 forRootView:(id)arg2;
- (void)setFrame:(struct CGRect)arg1 forView:(id)arg2;
- (id)viewForReactTag:(id)arg1;
- (void)registerRootView:(id)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
- (void)validateLayout;
- (void)invalidateLayout;
- (void)setBridge:(id)arg1;
- (id)viewRegistry;
- (id)shadowViewRegistry;
- (void)invalidate;
- (void)didReceiveNewContentSizeMultiplier;
- (id)allocateRootTag;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

