//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTViewManager.h"

#import "RCTWebViewDelegate.h"

@class NSConditionLock, NSString;

@interface RCTWebViewManager : RCTViewManager <RCTWebViewDelegate>
{
    NSConditionLock *_shouldStartLoadLock;
    BOOL _shouldStartLoad;
}

+ (id)__rct_export__1243;
+ (id)__rct_export__892;
+ (id)__rct_export__771;
+ (id)__rct_export__650;
+ (id)propConfig_allowsInlineMediaPlayback;
+ (id)propConfig_onShouldStartLoadWithRequest;
+ (id)propConfig_onLoadingError;
+ (id)propConfig_onLoadingFinish;
+ (id)propConfig_onLoadingStart;
+ (id)propConfig_automaticallyAdjustContentInsets;
+ (id)propConfig_contentInset;
+ (id)propConfig_injectedJavaScript;
+ (id)propConfig_scalesPageToFit;
+ (id)propConfig_scrollEnabled;
+ (id)propConfig_bounces;
+ (id)propConfig_html;
+ (id)propConfig_url;
+ (void)load;
+ (id)moduleName;
- (void).cxx_destruct;
- (void)startLoadWithResult:(BOOL)arg1 lockIdentifier:(int)arg2;
- (BOOL)webView:(id)arg1 shouldStartLoadForRequest:(id)arg2 withCallback:(CDUnknownBlockType)arg3;
- (void)reload:(id)arg1;
- (void)goForward:(id)arg1;
- (void)goBack:(id)arg1;
- (id)constantsToExport;
- (id)view;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

