//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoDataOutput, NSString;

@interface RTCAVFoundationVideoCapturerInternal : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    AVCaptureDeviceInput *_frontDeviceInput;
    AVCaptureDeviceInput *_backDeviceInput;
    AVCaptureVideoDataOutput *_videoOutput;
    struct AVFoundationVideoCapturer *_capturer;
    BOOL _orientationHasChanged;
    BOOL _useBackCamera;
    BOOL _isRunning;
    AVCaptureSession *_captureSession;
}

@property(readonly, nonatomic) BOOL isRunning; // @synthesize isRunning=_isRunning;
@property(nonatomic) BOOL useBackCamera; // @synthesize useBackCamera=_useBackCamera;
@property(readonly, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
- (void).cxx_destruct;
- (void)updateSessionInput;
- (void)updateOrientation;
- (void)deviceOrientationDidChange:(id)arg1;
- (BOOL)setupCaptureSession;
- (void)captureOutput:(id)arg1 didDropSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)stopCaptureAsync;
- (void)startCaptureAsync;
- (void)dealloc;
- (id)initWithCapturer:(struct AVFoundationVideoCapturer *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

