//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RTCVideoSource.h"

@class AVCaptureSession;

@interface RTCAVFoundationVideoSource : RTCVideoSource
{
}

@property(readonly, nonatomic) struct AVFoundationVideoCapturer *capturer;
@property(readonly, nonatomic) AVCaptureSession *captureSession;
@property(nonatomic) BOOL useBackCamera;
- (id)initWithFactory:(id)arg1 constraints:(id)arg2;

@end

