//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RTCMediaStreamTrack.h"

@interface RTCAudioTrack : RTCMediaStreamTrack
{
}

@property(readonly, nonatomic) scoped_refptr_833c0867 nativeAudioTrack;
- (id)initWithNativeTrack:(scoped_refptr_7d7e84a9)arg1 type:(int)arg2;
- (id)initWithFactory:(id)arg1 trackId:(id)arg2;

@end

