//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface RTCConfiguration : NSObject
{
    NSArray *_iceServers;
    int _iceTransportPolicy;
    int _bundlePolicy;
    int _rtcpMuxPolicy;
    int _tcpCandidatePolicy;
    int _audioJitterBufferMaxPackets;
    int _iceConnectionReceivingTimeout;
    int _iceBackupCandidatePairPingInterval;
    int _keyType;
}

+ (id)stringForTcpCandidatePolicy:(int)arg1;
+ (int)tcpCandidatePolicyForNativePolicy:(int)arg1;
+ (int)nativeTcpCandidatePolicyForPolicy:(int)arg1;
+ (id)stringForRtcpMuxPolicy:(int)arg1;
+ (int)rtcpMuxPolicyForNativePolicy:(int)arg1;
+ (int)nativeRtcpMuxPolicyForPolicy:(int)arg1;
+ (id)stringForBundlePolicy:(int)arg1;
+ (int)bundlePolicyForNativePolicy:(int)arg1;
+ (int)nativeBundlePolicyForPolicy:(int)arg1;
+ (id)stringForTransportPolicy:(int)arg1;
+ (int)transportPolicyForTransportsType:(int)arg1;
+ (int)nativeTransportsTypeForTransportPolicy:(int)arg1;
@property(nonatomic) int keyType; // @synthesize keyType=_keyType;
@property(nonatomic) int iceBackupCandidatePairPingInterval; // @synthesize iceBackupCandidatePairPingInterval=_iceBackupCandidatePairPingInterval;
@property(nonatomic) int iceConnectionReceivingTimeout; // @synthesize iceConnectionReceivingTimeout=_iceConnectionReceivingTimeout;
@property(nonatomic) int audioJitterBufferMaxPackets; // @synthesize audioJitterBufferMaxPackets=_audioJitterBufferMaxPackets;
@property(nonatomic) int tcpCandidatePolicy; // @synthesize tcpCandidatePolicy=_tcpCandidatePolicy;
@property(nonatomic) int rtcpMuxPolicy; // @synthesize rtcpMuxPolicy=_rtcpMuxPolicy;
@property(nonatomic) int bundlePolicy; // @synthesize bundlePolicy=_bundlePolicy;
@property(nonatomic) int iceTransportPolicy; // @synthesize iceTransportPolicy=_iceTransportPolicy;
@property(copy, nonatomic) NSArray *iceServers; // @synthesize iceServers=_iceServers;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct RTCConfiguration nativeConfiguration;
- (id)description;
- (id)init;

@end

