//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink;

@interface RTCDisplayLinkTimer : NSObject
{
    CADisplayLink *_displayLink;
    CDUnknownBlockType _timerHandler;
}

- (void).cxx_destruct;
- (void)displayLinkDidFire:(id)arg1;
- (void)invalidate;
@property(nonatomic) BOOL isPaused;
- (void)dealloc;
- (id)initWithTimerHandler:(CDUnknownBlockType)arg1;

@end

