//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RTCDataChannel : NSObject
{
    scoped_refptr_09a33b10 _nativDataChannel;
    struct scoped_ptr<webrtc::DataChannelDelegateAdapter, rtc::DefaultDeleter<webrtc::DataChannelDelegateAdapter>> _observer;
    BOOL _isObserverRegistered;
    id <RTCDataChannelDelegate> _delegate;
}

+ (id)stringForState:(int)arg1;
+ (int)dataChannelStateForNativeState:(int)arg1;
+ (int)nativeDataChannelStateForState:(int)arg1;
@property(nonatomic) __weak id <RTCDataChannelDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithNativeDataChannel:(scoped_refptr_09a33b10)arg1;
- (id)description;
- (BOOL)sendData:(id)arg1;
- (void)close;
@property(readonly, nonatomic) unsigned long long bufferedAmount;
@property(readonly, nonatomic) int readyState;
@property(readonly, nonatomic) int id;
@property(readonly, nonatomic) BOOL isNegotiated;
@property(readonly, nonatomic) NSString *protocol;
@property(readonly, nonatomic) unsigned short maxRetransmits;
@property(readonly, nonatomic) unsigned short maxPacketLifeTime;
@property(readonly, nonatomic) BOOL isOrdered;
@property(readonly, nonatomic) NSString *label;
- (void)dealloc;

@end

