//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface RTCIceServer : NSObject
{
    NSArray *_urlStrings;
    NSString *_username;
    NSString *_credential;
}

@property(readonly, copy, nonatomic) NSString *credential; // @synthesize credential=_credential;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, copy, nonatomic) NSArray *urlStrings; // @synthesize urlStrings=_urlStrings;
- (void).cxx_destruct;
- (id)initWithNativeServer:(struct IceServer)arg1;
@property(readonly, nonatomic) struct IceServer iceServer;
- (id)description;
- (id)initWithURLStrings:(id)arg1 username:(id)arg2 credential:(id)arg3;
- (id)initWithURLStrings:(id)arg1;

@end

