//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RTCMediaStreamTrack : NSObject
{
    scoped_refptr_7d7e84a9 _nativeTrack;
    int _type;
}

+ (id)stringForState:(int)arg1;
+ (int)trackStateForNativeState:(int)arg1;
+ (int)nativeTrackStateForState:(int)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithNativeTrack:(scoped_refptr_7d7e84a9)arg1 type:(int)arg2;
@property(readonly, nonatomic) scoped_refptr_7d7e84a9 nativeTrack;
- (id)description;
@property(readonly, nonatomic) int readyState;
@property(nonatomic) BOOL isEnabled;
@property(readonly, nonatomic) NSString *trackId;
@property(readonly, nonatomic) NSString *kind;

@end

