//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EAGLContext, RTCVideoFrame;

@interface RTCOpenGLVideoRenderer : NSObject
{
    EAGLContext *_context;
    BOOL _isInitialized;
    unsigned int _currentTextureSet;
    unsigned int _textures[6];
    unsigned int _program;
    unsigned int _vertexBuffer;
    int _position;
    int _texcoord;
    int _ySampler;
    int _uSampler;
    int _vSampler;
    struct scoped_ptr<unsigned char [], rtc::DefaultDeleter<unsigned char []>> _planeBuffer;
    RTCVideoFrame *_lastDrawnFrame;
}

+ (void)initialize;
@property(readonly, nonatomic) RTCVideoFrame *lastDrawnFrame; // @synthesize lastDrawnFrame=_lastDrawnFrame;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)setupVertices;
- (BOOL)updateTextureDataForFrame:(id)arg1;
- (void)uploadPlane:(const char *)arg1 sampler:(int)arg2 offset:(unsigned int)arg3 width:(unsigned long)arg4 height:(unsigned long)arg5 stride:(int)arg6;
- (BOOL)updateTextureSizesForFrame:(id)arg1;
- (BOOL)setupTextures;
- (BOOL)setupProgram;
- (void)ensureGLContext;
- (void)teardownGL;
- (void)setupGL;
- (BOOL)drawFrame:(id)arg1;
- (id)initWithContext:(id)arg1;

@end

