//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RTCSessionDescription : NSObject
{
    int _type;
    NSString *_sdp;
}

+ (int)typeForString:(const basic_string_7d00a7a9 *)arg1;
+ (basic_string_7d00a7a9)stringForType:(int)arg1;
@property(readonly, nonatomic) NSString *sdp; // @synthesize sdp=_sdp;
@property(readonly, nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithNativeDescription:(const struct SessionDescriptionInterface *)arg1;
@property(readonly, nonatomic) struct SessionDescriptionInterface *nativeDescription;
- (id)description;
- (id)initWithType:(int)arg1 sdp:(id)arg2;

@end

