//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureConnection, AVCaptureSession, NSCondition, NSString;

@interface RTCVideoCaptureIosObjC : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    struct VideoCaptureIos *_owner;
    struct VideoCaptureCapability _capability;
    AVCaptureSession *_captureSession;
    int _captureId;
    BOOL _orientationHasChanged;
    AVCaptureConnection *_connection;
    BOOL _captureChanging;
    NSCondition *_captureChangingCondition;
    int _framRotation;
}

@property int frameRotation; // @synthesize frameRotation=_framRotation;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)waitForCaptureChangeToFinish;
- (void)signalCaptureChangeEnd;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (BOOL)changeCaptureInputByUniqueId:(id)arg1;
- (void)stopCaptureInBackground;
- (BOOL)stopCapture;
- (void)onVideoError:(id)arg1;
- (void)setRelativeVideoOrientation;
- (void)startCaptureInBackgroundWithOutput:(id)arg1;
- (id)currentOutput;
- (BOOL)startCaptureWithCapability:(const struct VideoCaptureCapability *)arg1;
- (BOOL)setCaptureDeviceByUniqueId:(id)arg1;
- (void)dealloc;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)directOutputToNil;
- (void)directOutputToSelf;
- (id)initWithOwner:(struct VideoCaptureIos *)arg1 captureId:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

