//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RTCVideoSource : NSObject
{
    scoped_refptr_6f9579bc _nativeVideoSource;
}

+ (id)stringForState:(int)arg1;
+ (int)sourceStateForNativeState:(int)arg1;
+ (int)nativeSourceStateForState:(int)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithNativeVideoSource:(scoped_refptr_6f9579bc)arg1;
@property(readonly, nonatomic) scoped_refptr_6f9579bc nativeVideoSource;
- (id)description;
@property(readonly, nonatomic) int state;

@end

