//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RTCVideoRendererAdapter : NSObject
{
    struct scoped_ptr<webrtc::VideoRendererAdapter, rtc::DefaultDeleter<webrtc::VideoRendererAdapter>> _adapter;
    id <RTCVideoRenderer> _videoRenderer;
}

@property(readonly, nonatomic) id <RTCVideoRenderer> videoRenderer; // @synthesize videoRenderer=_videoRenderer;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct VideoRendererInterface *nativeVideoRenderer;
- (id)initWithNativeRenderer:(id)arg1;

@end

