//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RTCVideoFrame : NSObject
{
    struct scoped_ptr<cricket::VideoFrame, rtc::DefaultDeleter<cricket::VideoFrame>> _videoFrame;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithNativeFrame:(const struct VideoFrame *)arg1;
@property(readonly, nonatomic) int vPitch;
@property(readonly, nonatomic) int uPitch;
@property(readonly, nonatomic) int yPitch;
@property(readonly, nonatomic) const char *vPlane;
@property(readonly, nonatomic) const char *uPlane;
@property(readonly, nonatomic) const char *yPlane;
@property(readonly, nonatomic) unsigned long chromaSize;
@property(readonly, nonatomic) unsigned long chromaHeight;
@property(readonly, nonatomic) unsigned long chromaWidth;
@property(readonly, nonatomic) unsigned long height;
@property(readonly, nonatomic) unsigned long width;

@end

