//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class NSArray, NSMutableArray, NSString, UIColor, UILabel;

@interface SLKTextView : UITextView
{
    BOOL _didNotResignFirstResponder;
    BOOL _loupeVisible;
    BOOL _trackpadEnabled;
    BOOL _undoManagerEnabled;
    BOOL _dynamicTypeEnabled;
    BOOL _didFlashScrollIndicators;
    BOOL _formatting;
    unsigned int _maxNumberOfLines;
    unsigned int _pastableMediaTypes;
    UILabel *_placeholderLabel;
    float _initialFontSize;
    NSArray *_keyboardCommands;
    int _verticalMoveDirection;
    NSMutableArray *_registeredFormattingTitles;
    NSMutableArray *_registeredFormattingSymbols;
    struct CGRect _verticalMoveStartCaretRect;
    struct CGRect _verticalMoveLastCaretRect;
}

+ (BOOL)requiresConstraintBasedLayout;
+ (float)pointSizeDifferenceForCategory:(id)arg1;
@property(nonatomic, getter=isFormatting) BOOL formatting; // @synthesize formatting=_formatting;
@property(retain, nonatomic) NSMutableArray *registeredFormattingSymbols; // @synthesize registeredFormattingSymbols=_registeredFormattingSymbols;
@property(retain, nonatomic) NSMutableArray *registeredFormattingTitles; // @synthesize registeredFormattingTitles=_registeredFormattingTitles;
@property(nonatomic) BOOL didFlashScrollIndicators; // @synthesize didFlashScrollIndicators=_didFlashScrollIndicators;
@property(nonatomic) struct CGRect verticalMoveLastCaretRect; // @synthesize verticalMoveLastCaretRect=_verticalMoveLastCaretRect;
@property(nonatomic) struct CGRect verticalMoveStartCaretRect; // @synthesize verticalMoveStartCaretRect=_verticalMoveStartCaretRect;
@property(nonatomic) int verticalMoveDirection; // @synthesize verticalMoveDirection=_verticalMoveDirection;
@property(retain, nonatomic) NSArray *keyboardCommands; // @synthesize keyboardCommands=_keyboardCommands;
@property(nonatomic) float initialFontSize; // @synthesize initialFontSize=_initialFontSize;
@property(retain, nonatomic) UILabel *placeholderLabel; // @synthesize placeholderLabel=_placeholderLabel;
@property(nonatomic, getter=isDynamicTypeEnabled) BOOL dynamicTypeEnabled; // @synthesize dynamicTypeEnabled=_dynamicTypeEnabled;
@property(nonatomic) BOOL undoManagerEnabled; // @synthesize undoManagerEnabled=_undoManagerEnabled;
@property(readonly, nonatomic, getter=isTrackpadEnabled) BOOL trackpadEnabled; // @synthesize trackpadEnabled=_trackpadEnabled;
@property(nonatomic, getter=isLoupeVisible) BOOL loupeVisible; // @synthesize loupeVisible=_loupeVisible;
@property(nonatomic) BOOL didNotResignFirstResponder; // @synthesize didNotResignFirstResponder=_didNotResignFirstResponder;
@property(nonatomic) unsigned int pastableMediaTypes; // @synthesize pastableMediaTypes=_pastableMediaTypes;
@property(nonatomic) unsigned int maxNumberOfLines; // @synthesize maxNumberOfLines=_maxNumberOfLines;
- (void).cxx_destruct;
- (void)dealloc;
- (void)slk_unregisterNotifications;
- (void)slk_registerNotifications;
- (BOOL)slk_isNewVerticalMovementForPosition:(id)arg1 inDirection:(int)arg2;
- (id)slk_closestPositionToPosition:(id)arg1 inDirection:(int)arg2;
- (void)slk_moveCursorTodirection:(int)arg1;
- (void)didPressAnyArrowKey:(id)arg1;
- (void)slk_didPressCommandZKeys:(id)arg1;
- (void)slk_didPressLineBreakKeys:(id)arg1;
- (id)keyCommands;
- (void)motionEnded:(int)arg1 withEvent:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)slk_didHideMenuController:(id)arg1;
- (void)slk_willShowMenuController:(id)arg1;
- (void)slk_didChangeContentSizeCategory:(id)arg1;
- (void)slk_didChangeTextInputMode:(id)arg1;
- (void)slk_didEndEditing:(id)arg1;
- (void)slk_didChangeText:(id)arg1;
- (void)slk_didBeginEditing:(id)arg1;
@property(readonly, nonatomic) NSArray *registeredSymbols;
- (void)registerMarkdownFormattingSymbol:(id)arg1 withTitle:(id)arg2;
- (void)slk_format:(id)arg1;
- (id)slk_formattingSymbolWithTitle:(id)arg1;
- (id)slk_formattingTitleFromSelector:(SEL)arg1;
- (void)slk_presentFormattingMenu:(id)arg1;
- (void)slk_redo:(id)arg1;
- (void)slk_undo:(id)arg1;
- (void)slk_addCustomMenuControllerItems;
- (void)refreshInputViews;
- (void)refreshFirstResponder;
- (void)slk_flashScrollIndicatorsIfNeeded;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)paste:(id)arg1;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (BOOL)resignFirstResponder;
- (BOOL)canResignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (void)endFloatingCursor;
- (void)updateFloatingCursorAtPoint:(struct CGPoint)arg1;
- (void)beginFloatingCursorAtPoint:(struct CGPoint)arg1;
- (void)setTextAlignment:(int)arg1;
- (void)setFontName:(id)arg1 pointSize:(float)arg2 withContentSizeCategory:(id)arg3;
- (void)setFont:(id)arg1;
- (void)setAttributedText:(id)arg1;
- (void)setText:(id)arg1;
- (void)setSelectedTextRange:(id)arg1;
- (void)setSelectedRange:(struct _NSRange)arg1;
@property(nonatomic, getter=isTypingSuggestionEnabled) BOOL typingSuggestionEnabled;
@property(copy, nonatomic) UIColor *placeholderColor;
@property(copy, nonatomic) NSString *placeholder;
- (struct CGRect)slk_placeholderRectThatFits:(struct CGRect)arg1;
- (BOOL)slk_shouldHidePlaceholder;
@property(readonly, nonatomic) BOOL isExpanding;
- (id)slk_supportedMediaTypes;
- (id)slk_pasteboardContentType;
- (BOOL)slk_isPasteboardItemSupported;
- (id)slk_pastedItem;
@property(readonly, nonatomic, getter=isFormattingEnabled) BOOL formattingEnabled;
@property(readonly, nonatomic) unsigned int numberOfLines;
- (void)layoutSubviews;
- (void)layoutIfNeeded;
- (struct CGSize)intrinsicContentSize;
- (void)slk_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;
- (void)slk_prepareForUndo:(id)arg1;
- (id)slk_wordAtRange:(struct _NSRange)arg1 rangeInText:(struct _NSRange *)arg2;
- (id)slk_wordAtCaretRange:(struct _NSRange *)arg1;
- (struct _NSRange)slk_insertText:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)slk_insertTextAtCaretRange:(id)arg1;
- (void)slk_insertNewLineBreak;
- (void)slk_scrollToBottomAnimated:(BOOL)arg1;
- (void)slk_scrollToCaretPositonAnimated:(BOOL)arg1;
- (void)slk_clearText:(BOOL)arg1;

// Remaining properties
@property(nonatomic) __weak id <SLKTextViewDelegate><UITextViewDelegate> delegate; // @dynamic delegate;

@end

