//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SLKTextViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSLayoutConstraint, NSString, SLKTextInputbar, SLKTextView, SLKTypingIndicatorView, UIButton, UICollectionView, UIGestureRecognizer, UIPanGestureRecognizer, UIScrollView, UITableView, UIView, UIView<SLKTypingIndicatorProtocol>;

@interface SLKTextViewController : UIViewController <SLKTextViewDelegate, UITableViewDelegate, UITableViewDataSource, UICollectionViewDelegate, UICollectionViewDataSource, UIGestureRecognizerDelegate, UIAlertViewDelegate>
{
    struct CGPoint _scrollViewOffsetBeforeDragging;
    float _keyboardHeightBeforeDragging;
    BOOL _autoCompleting;
    BOOL _presentedInPopover;
    BOOL _bounces;
    BOOL _shakeToClearEnabled;
    BOOL _keyboardPanningEnabled;
    BOOL _externalKeyboardDetected;
    BOOL _keyboardUndocked;
    BOOL _shouldClearTextAtRightButtonPress;
    BOOL _shouldScrollToBottomAfterKeyboardShows;
    BOOL _inverted;
    BOOL _textInputbarHidden;
    BOOL _editing;
    BOOL _movingKeyboard;
    BOOL _viewVisible;
    BOOL _transitioning;
    UITableView *_tableView;
    UICollectionView *_collectionView;
    UIScrollView *_scrollView;
    UIView<SLKTypingIndicatorProtocol> *_typingIndicatorProxyView;
    SLKTextInputbar *_textInputbar;
    UITableView *_autoCompletionView;
    UIScrollView *_scrollViewProxy;
    UIGestureRecognizer *_singleTapGesture;
    UIPanGestureRecognizer *_verticalPanGesture;
    NSString *_foundPrefix;
    NSString *_foundWord;
    NSArray *_registeredPrefixes;
    UIView *_autoCompletionHairline;
    NSLayoutConstraint *_scrollViewHC;
    NSLayoutConstraint *_textInputbarHC;
    NSLayoutConstraint *_typingIndicatorViewHC;
    NSLayoutConstraint *_autoCompletionViewHC;
    NSLayoutConstraint *_keyboardHC;
    unsigned int _keyboardStatus;
    Class _textViewClass;
    Class _typingIndicatorViewClass;
    struct _NSRange _foundPrefixRange;
}

+ (void)clearAllCachedText;
+ (id)collectionViewLayoutForCoder:(id)arg1;
+ (int)tableViewStyleForCoder:(id)arg1;
@property(retain, nonatomic) Class typingIndicatorViewClass; // @synthesize typingIndicatorViewClass=_typingIndicatorViewClass;
@property(retain, nonatomic) Class textViewClass; // @synthesize textViewClass=_textViewClass;
@property(nonatomic, getter=isTransitioning) BOOL transitioning; // @synthesize transitioning=_transitioning;
@property(nonatomic, getter=isViewVisible) BOOL viewVisible; // @synthesize viewVisible=_viewVisible;
@property(nonatomic) unsigned int keyboardStatus; // @synthesize keyboardStatus=_keyboardStatus;
@property(nonatomic, getter=isMovingKeyboard) BOOL movingKeyboard; // @synthesize movingKeyboard=_movingKeyboard;
@property(retain, nonatomic) NSLayoutConstraint *keyboardHC; // @synthesize keyboardHC=_keyboardHC;
@property(retain, nonatomic) NSLayoutConstraint *autoCompletionViewHC; // @synthesize autoCompletionViewHC=_autoCompletionViewHC;
@property(retain, nonatomic) NSLayoutConstraint *typingIndicatorViewHC; // @synthesize typingIndicatorViewHC=_typingIndicatorViewHC;
@property(retain, nonatomic) NSLayoutConstraint *textInputbarHC; // @synthesize textInputbarHC=_textInputbarHC;
@property(retain, nonatomic) NSLayoutConstraint *scrollViewHC; // @synthesize scrollViewHC=_scrollViewHC;
@property(retain, nonatomic) UIView *autoCompletionHairline; // @synthesize autoCompletionHairline=_autoCompletionHairline;
@property(readonly, copy, nonatomic) NSArray *registeredPrefixes; // @synthesize registeredPrefixes=_registeredPrefixes;
@property(readonly, copy, nonatomic) NSString *foundWord; // @synthesize foundWord=_foundWord;
@property(readonly, nonatomic) struct _NSRange foundPrefixRange; // @synthesize foundPrefixRange=_foundPrefixRange;
@property(readonly, copy, nonatomic) NSString *foundPrefix; // @synthesize foundPrefix=_foundPrefix;
@property(readonly, nonatomic, getter=isEditing) BOOL editing; // @synthesize editing=_editing;
@property(nonatomic, getter=isTextInputbarHidden) BOOL textInputbarHidden; // @synthesize textInputbarHidden=_textInputbarHidden;
@property(nonatomic, getter=isInverted) BOOL inverted; // @synthesize inverted=_inverted;
@property(nonatomic) BOOL shouldScrollToBottomAfterKeyboardShows; // @synthesize shouldScrollToBottomAfterKeyboardShows=_shouldScrollToBottomAfterKeyboardShows;
@property(nonatomic) BOOL shouldClearTextAtRightButtonPress; // @synthesize shouldClearTextAtRightButtonPress=_shouldClearTextAtRightButtonPress;
@property(readonly, nonatomic, getter=isKeyboardUndocked) BOOL keyboardUndocked; // @synthesize keyboardUndocked=_keyboardUndocked;
@property(readonly, nonatomic, getter=isExternalKeyboardDetected) BOOL externalKeyboardDetected; // @synthesize externalKeyboardDetected=_externalKeyboardDetected;
@property(nonatomic, getter=isKeyboardPanningEnabled) BOOL keyboardPanningEnabled; // @synthesize keyboardPanningEnabled=_keyboardPanningEnabled;
@property(nonatomic) BOOL shakeToClearEnabled; // @synthesize shakeToClearEnabled=_shakeToClearEnabled;
@property(nonatomic) BOOL bounces; // @synthesize bounces=_bounces;
@property(readonly, nonatomic) UIPanGestureRecognizer *verticalPanGesture; // @synthesize verticalPanGesture=_verticalPanGesture;
@property(readonly, nonatomic) UIGestureRecognizer *singleTapGesture; // @synthesize singleTapGesture=_singleTapGesture;
@property(nonatomic, getter=isPresentedInPopover) BOOL presentedInPopover; // @synthesize presentedInPopover=_presentedInPopover;
@property(nonatomic) __weak UIScrollView *scrollViewProxy; // @synthesize scrollViewProxy=_scrollViewProxy;
@property(readonly, nonatomic, getter=isAutoCompleting) BOOL autoCompleting; // @synthesize autoCompleting=_autoCompleting;
@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotate;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)slk_unregisterNotifications;
- (void)slk_registerNotifications;
- (id)slk_arrowKeyCommand:(id)arg1;
- (id)slk_escKeyCommand;
- (id)slk_returnKeyCommand;
- (id)keyCommands;
- (void)slk_updateViewConstraints;
- (void)slk_setupViewConstraints;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (BOOL)textView:(id)arg1 shouldInsertSuffixForFormattingWithSymbol:(id)arg2 prefixRange:(struct _NSRange)arg3;
- (BOOL)textView:(id)arg1 shouldOfferFormattingForSymbol:(id)arg2;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (BOOL)textViewShouldEndEditing:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)registerClassForTypingIndicatorView:(Class)arg1;
- (void)registerClassForTextView:(Class)arg1;
- (void)slk_cacheTextToDisk:(id)arg1;
- (void)clearCachedText;
- (void)slk_cacheTextView;
- (void)slk_reloadTextView;
- (id)slk_keyForPersistency;
- (id)keyForTextCaching;
- (void)slk_hideAutoCompletionViewIfNeeded;
- (void)slk_invalidateAutoCompletion;
- (void)slk_handleProcessedWord:(id)arg1 range:(struct _NSRange)arg2;
- (void)slk_processTextForAutoCompletion;
- (void)cancelAutoCompletion;
- (void)acceptAutoCompletionWithString:(id)arg1 keepPrefix:(BOOL)arg2;
- (void)acceptAutoCompletionWithString:(id)arg1;
- (void)showAutoCompletionView:(BOOL)arg1;
- (BOOL)canShowAutoCompletion;
- (void)didChangeAutoCompletionPrefix:(id)arg1 andWord:(id)arg2;
- (void)registerPrefixesForAutoCompletion:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)slk_willTerminateApplication:(id)arg1;
- (void)slk_willShowOrHideTypeIndicatorView:(id)arg1;
- (void)slk_didShakeTextView:(id)arg1;
- (void)slk_didChangeTextViewPasteboard:(id)arg1;
- (void)slk_didChangeTextViewSelectedRange:(id)arg1;
- (void)slk_didChangeTextViewContentSize:(id)arg1;
- (void)slk_didChangeTextViewText:(id)arg1;
- (void)slk_willChangeTextViewText:(id)arg1;
- (void)slk_didPostSLKKeyboardNotification:(id)arg1;
- (void)slk_didShowOrHideKeyboard:(id)arg1;
- (void)slk_willShowOrHideKeyboard:(id)arg1;
- (void)didPressArrowKey:(id)arg1;
- (void)didPressEscapeKey:(id)arg1;
- (void)didPressReturnKey:(id)arg1;
- (void)slk_prepareForInterfaceTransitionWithDuration:(double)arg1;
- (void)slk_adjustContentConfigurationIfNeeded;
- (void)slk_detectKeyboardStatesInNotification:(id)arg1;
- (void)slk_dismissTextInputbarIfNeeded;
- (void)slk_enableTypingSuggestionIfNeeded;
- (void)slk_postKeyboarStatusNotification:(id)arg1;
- (void)slk_performRightAction;
- (void)slk_didPanTextView:(id)arg1;
- (void)slk_didTapScrollView:(id)arg1;
- (void)slk_handlePanGestureRecognizer:(id)arg1;
- (void)slk_didPanTextInputBar:(id)arg1;
- (void)setTextInputbarHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)willRequestUndo;
- (void)didPasteMediaContent:(id)arg1;
- (float)maximumHeightForAutoCompletionView;
- (float)heightForAutoCompletionView;
- (BOOL)canShowTypingIndicator;
- (void)didCancelTextEditing:(id)arg1;
- (void)didCommitTextEditing:(id)arg1;
- (void)editText:(id)arg1;
- (void)didPressRightButton:(id)arg1;
- (void)didPressLeftButton:(id)arg1;
- (BOOL)canPressRightButton;
- (void)textSelectionDidChange;
- (void)textDidUpdate:(BOOL)arg1;
- (void)textWillUpdate;
- (void)didChangeKeyboardStatus:(unsigned int)arg1;
- (BOOL)ignoreTextInputbarAdjustment;
- (BOOL)forceTextInputbarAdjustmentForResponder:(id)arg1;
- (void)dismissKeyboard:(BOOL)arg1;
- (void)presentKeyboard:(BOOL)arg1;
- (BOOL)slk_updateKeyboardStatus:(unsigned int)arg1;
- (void)setAutoCompleting:(BOOL)arg1;
- (void)setEdgesForExtendedLayout:(unsigned int)arg1;
- (BOOL)slk_isIllogicalKeyboardStatus:(unsigned int)arg1;
- (unsigned int)slk_keyboardStatusForNotification:(id)arg1;
- (id)slk_appropriateKeyboardNotificationName:(id)arg1;
- (float)slk_topBarsHeight;
- (float)slk_appropriateScrollViewHeight;
- (float)slk_appropriateBottomMargin;
- (float)slk_appropriateKeyboardHeightFromRect:(struct CGRect)arg1;
- (float)slk_appropriateKeyboardHeightFromNotification:(id)arg1;
- (int)modalPresentationStyle;
@property(readonly, nonatomic) UIButton *rightButton;
@property(readonly, nonatomic) UIButton *leftButton;
@property(readonly, nonatomic) SLKTextView *textView;
@property(readonly, nonatomic) SLKTypingIndicatorView *typingIndicatorView;
@property(readonly, nonatomic) UIView<SLKTypingIndicatorProtocol> *typingIndicatorProxyView; // @synthesize typingIndicatorProxyView=_typingIndicatorProxyView;
@property(readonly, nonatomic) SLKTextInputbar *textInputbar; // @synthesize textInputbar=_textInputbar;
@property(readonly, nonatomic) UITableView *autoCompletionView; // @synthesize autoCompletionView=_autoCompletionView;
- (id)collectionViewWithLayout:(id)arg1;
- (id)tableViewWithStyle:(int)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)slk_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithScrollView:(id)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)initWithTableViewStyle:(int)arg1;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

