//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class HNKCacheFormat;

@interface UIButton (Haneke)
+ (void)setNetworkFetcherClass:(Class)arg1;
+ (Class)networkFetcherClass;
- (void)setHnk_backgroundImageFetcher:(id)arg1;
- (id)hnk_backgroundImageFetcher;
- (BOOL)hnk_shouldCancelSetBackgroundImageForKey:(id)arg1;
- (void)hnk_setBackgroundImage:(id)arg1 forState:(unsigned int)arg2 animated:(BOOL)arg3 success:(CDUnknownBlockType)arg4;
- (BOOL)hnk_fetchBackgroundImageFromFetcher:(id)arg1 forState:(unsigned int)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) HNKCacheFormat *hnk_backgroundImageFormat;
- (void)hnk_cancelSetBackgroundImage;
- (void)hnk_setBackgroundImageFromFetcher:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)hnk_setBackgroundImageFromFetcher:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3;
- (void)hnk_setBackgroundImageFromFetcher:(id)arg1 forState:(unsigned int)arg2;
- (void)hnk_setBackgroundImage:(id)arg1 withKey:(id)arg2 forState:(unsigned int)arg3 placeholder:(id)arg4;
- (void)hnk_setBackgroundImage:(id)arg1 withKey:(id)arg2 forState:(unsigned int)arg3;
- (void)hnk_setBackgroundImage:(id)arg1 withKey:(id)arg2 forState:(unsigned int)arg3 placeholder:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)hnk_setBackgroundImageFromFile:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)hnk_setBackgroundImageFromFile:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3;
- (void)hnk_setBackgroundImageFromFile:(id)arg1 forState:(unsigned int)arg2;
- (void)hnk_setBackgroundImageFromURL:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)hnk_setBackgroundImageFromURL:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3;
- (void)hnk_setBackgroundImageFromURL:(id)arg1 forState:(unsigned int)arg2;
- (void)setHnk_imageFetcher:(id)arg1;
- (id)hnk_imageFetcher;
- (BOOL)hnk_shouldCancelSetImageForKey:(id)arg1;
- (void)hnk_setImage:(id)arg1 forState:(unsigned int)arg2 animated:(BOOL)arg3 success:(CDUnknownBlockType)arg4;
- (BOOL)hnk_fetchImageFromFetcher:(id)arg1 forState:(unsigned int)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) HNKCacheFormat *hnk_imageFormat;
- (void)hnk_cancelSetImage;
- (void)hnk_setImageFromFetcher:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)hnk_setImageFromFetcher:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3;
- (void)hnk_setImageFromFetcher:(id)arg1 forState:(unsigned int)arg2;
- (void)hnk_setImage:(id)arg1 withKey:(id)arg2 forState:(unsigned int)arg3 placeholder:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)hnk_setImage:(id)arg1 withKey:(id)arg2 forState:(unsigned int)arg3 placeholder:(id)arg4;
- (void)hnk_setImage:(id)arg1 withKey:(id)arg2 forState:(unsigned int)arg3;
- (void)hnk_setImageFromFile:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)hnk_setImageFromFile:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3;
- (void)hnk_setImageFromFile:(id)arg1 forState:(unsigned int)arg2;
- (void)hnk_setImageFromURL:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)hnk_setImageFromURL:(id)arg1 forState:(unsigned int)arg2 placeholder:(id)arg3;
- (void)hnk_setImageFromURL:(id)arg1 forState:(unsigned int)arg2;
@end

