//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CKAsyncTransactionContainer.h"

@interface UIView (CKAsyncTransactionContainer) <CKAsyncTransactionContainer>
- (void)ck_asyncTransactionContainerStateDidChange;
- (void)ck_cancelAsyncTransactions;
@property(readonly, nonatomic) unsigned int ck_asyncTransactionContainerState;
@property(nonatomic, getter=ck_isAsyncTransactionContainer, setter=ck_setAsyncTransactionContainer:) BOOL ck_asyncTransactionContainer;
@end

