//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "DCDBundleUpdaterDelegate.h"
#import "UIApplicationDelegate.h"

@class DCDBundleUpdater, NSString, UIWindow;

@interface AppDelegate : UIResponder <UIApplicationDelegate, DCDBundleUpdaterDelegate>
{
    UIWindow *_window;
    DCDBundleUpdater *_updater;
}

+ (void)initialize;
@property(retain, nonatomic) DCDBundleUpdater *updater; // @synthesize updater=_updater;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)startWithBundleURL:(id)arg1 launchOptions:(id)arg2;
- (void)bundleChangeStatus:(long long)arg1;
- (void)bundleUpdaterReady:(id)arg1;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

