//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface BugsnagCrashReport : NSObject
{
    NSArray *_notifyReleaseStages;
    NSString *_context;
    unsigned long long _severity;
    NSString *_releaseStage;
    NSString *_errorClass;
    NSString *_errorMessage;
    NSString *_groupingHash;
    NSArray *_breadcrumbs;
    NSDictionary *_metaData;
    NSDictionary *_overrides;
    unsigned long long _depth;
    NSDictionary *_error;
    NSDictionary *_device;
    NSDictionary *_deviceState;
    NSDictionary *_app;
    NSDictionary *_appState;
    NSString *_errorType;
    NSString *_dsymUUID;
    NSString *_deviceAppHash;
    NSArray *_binaryImages;
    NSArray *_threads;
    NSDictionary *_customException;
}

@property(copy, nonatomic) NSDictionary *customException; // @synthesize customException=_customException;
@property(readonly, copy, nonatomic) NSArray *threads; // @synthesize threads=_threads;
@property(readonly, copy, nonatomic) NSArray *binaryImages; // @synthesize binaryImages=_binaryImages;
@property(readonly, copy, nonatomic) NSString *deviceAppHash; // @synthesize deviceAppHash=_deviceAppHash;
@property(readonly, copy, nonatomic) NSString *dsymUUID; // @synthesize dsymUUID=_dsymUUID;
@property(copy, nonatomic) NSString *errorType; // @synthesize errorType=_errorType;
@property(copy, nonatomic) NSDictionary *appState; // @synthesize appState=_appState;
@property(copy, nonatomic) NSDictionary *app; // @synthesize app=_app;
@property(copy, nonatomic) NSDictionary *deviceState; // @synthesize deviceState=_deviceState;
@property(copy, nonatomic) NSDictionary *device; // @synthesize device=_device;
@property(copy, nonatomic) NSDictionary *error; // @synthesize error=_error;
@property(nonatomic) unsigned long long depth; // @synthesize depth=_depth;
@property(readonly, copy, nonatomic) NSDictionary *overrides; // @synthesize overrides=_overrides;
@property(copy, nonatomic) NSDictionary *metaData; // @synthesize metaData=_metaData;
@property(copy, nonatomic) NSArray *breadcrumbs; // @synthesize breadcrumbs=_breadcrumbs;
@property(copy, nonatomic) NSString *groupingHash; // @synthesize groupingHash=_groupingHash;
@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(copy, nonatomic) NSString *errorClass; // @synthesize errorClass=_errorClass;
@property(copy, nonatomic) NSString *releaseStage; // @synthesize releaseStage=_releaseStage;
@property(nonatomic) unsigned long long severity; // @synthesize severity=_severity;
@property(copy, nonatomic) NSString *context; // @synthesize context=_context;
@property(copy, nonatomic) NSArray *notifyReleaseStages; // @synthesize notifyReleaseStages=_notifyReleaseStages;
- (void).cxx_destruct;
- (id)serializeThreadsWithException:(id)arg1;
- (id)serializableValueWithTopLevelData:(id)arg1;
- (void)setOverrideProperty:(id)arg1 value:(id)arg2;
- (void)attachCustomStacktrace:(id)arg1 withType:(id)arg2;
- (_Bool)shouldBeSent;
- (id)initWithErrorName:(id)arg1 errorMessage:(id)arg2 configuration:(id)arg3 metaData:(id)arg4 severity:(unsigned long long)arg5;
- (id)initWithKSReport:(id)arg1;

@end

