//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BugsnagMetaDataDelegate.h"

@class BugsnagConfiguration, BugsnagMetaData, NSDictionary, NSLock, NSString;

@interface BugsnagNotifier : NSObject <BugsnagMetaDataDelegate>
{
    BugsnagConfiguration *configuration;
    BugsnagMetaData *_state;
    NSDictionary *_details;
    NSLock *_metaDataLock;
}

@property(retain, nonatomic) NSLock *metaDataLock; // @synthesize metaDataLock=_metaDataLock;
@property(retain, nonatomic) NSDictionary *details; // @synthesize details=_details;
@property(retain, nonatomic) BugsnagMetaData *state; // @synthesize state=_state;
@property(retain, nonatomic) BugsnagConfiguration *configuration; // @synthesize configuration;
- (void).cxx_destruct;
- (void)sendBreadcrumbForControlNotification:(id)arg1;
- (void)sendBreadcrumbForMenuItemNotification:(id)arg1;
- (void)sendBreadcrumbForTableViewNotification:(id)arg1;
- (void)sendBreadcrumbForNotification:(id)arg1;
- (void)dealloc;
- (void)crumbleNotification:(id)arg1;
- (id)automaticBreadcrumbMenuItemEvents;
- (id)automaticBreadcrumbTableItemEvents;
- (id)automaticBreadcrumbControlEvents;
- (id)automaticBreadcrumbStateEvents;
- (void)updateAutomaticBreadcrumbDetectionSettings;
- (void)lowMemoryWarning:(id)arg1;
- (void)orientationChanged:(id)arg1;
- (void)batteryChanged:(id)arg1;
- (void)metaDataChanged:(id)arg1;
- (void)sendPendingReports;
- (void)serializeBreadcrumbs;
- (void)clearBreadcrumbs;
- (void)addBreadcrumbWithBlock:(CDUnknownBlockType)arg1;
- (void)notify:(id)arg1 message:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)notifyException:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)notifyError:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)start;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

