//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CKTransactionalComponentDataSourceListener.h"
#import "UICollectionViewDataSource.h"

@class CKComponentDataSourceAttachController, CKTransactionalComponentDataSource, CKTransactionalComponentDataSourceState, NSString, UICollectionView;

@interface CKCollectionViewTransactionalDataSource : NSObject <UICollectionViewDataSource, CKTransactionalComponentDataSourceListener>
{
    CKTransactionalComponentDataSource *_componentDataSource;
    id <CKSupplementaryViewDataSource> _supplementaryViewDataSource;
    CKTransactionalComponentDataSourceState *_currentState;
    CKComponentDataSourceAttachController *_attachController;
    UICollectionView *_collectionView;
}

@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(readonly, nonatomic) __weak id <CKSupplementaryViewDataSource> supplementaryViewDataSource; // @synthesize supplementaryViewDataSource=_supplementaryViewDataSource;
- (void).cxx_destruct;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)updateConfiguration:(id)arg1 mode:(unsigned long long)arg2 userInfo:(id)arg3;
- (void)reloadWithMode:(unsigned long long)arg1 userInfo:(id)arg2;
- (struct CGSize)sizeForItemAtIndexPath:(id)arg1;
- (id)modelForItemAtIndexPath:(id)arg1;
- (void)_detachComponentLayoutForRemovedItemsAtIndexPaths:(id)arg1 inState:(id)arg2;
- (void)transactionalComponentDataSource:(id)arg1 didModifyPreviousState:(id)arg2 byApplyingChanges:(id)arg3;
- (void)applyChangeset:(id)arg1 mode:(unsigned long long)arg2 userInfo:(id)arg3;
- (id)initWithCollectionView:(id)arg1 supplementaryViewDataSource:(id)arg2 configuration:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

