//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CKComponentDebugController : NSObject
{
}

+ (void)reflowComponentsForView:(id)arg1 searchUpwards:(_Bool)arg2;
+ (void)reflowComponents;
+ (_Bool)debugMode;
+ (void)setDebugMode:(_Bool)arg1;

@end

