//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKComponentPreparationQueue;

@protocol CKComponentPreparationQueueListener <NSObject>
- (void)componentPreparationQueue:(CKComponentPreparationQueue *)arg1 didFinishPreparingBatchOfSize:(unsigned long long)arg2 batchID:(unsigned long long)arg3;
- (void)componentPreparationQueue:(CKComponentPreparationQueue *)arg1 didStartPreparingBatchOfSize:(unsigned long long)arg2 batchID:(unsigned long long)arg3;
@end

