//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKComponent.h"

@interface CKTextComponent : CKComponent
{
    struct CKTextKitAttributes _attributes;
    struct CKTextComponentAccessibilityContext _accessibilityContext;
}

+ (id)newWithTextAttributes:(const struct CKTextKitAttributes *)arg1 viewAttributes:(const unordered_map_6bb69700 *)arg2 options:(const struct CKTextComponentOptions *)arg3 size:(const struct CKComponentSize *)arg4;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct MountResult)mountInContext:(const struct MountContext *)arg1 size:(struct CGSize)arg2 children:(shared_ptr_6a94d7a4)arg3 supercomponent:(id)arg4;
- (struct CKComponentLayout)computeLayoutThatFits:(struct CKSizeRange)arg1;

@end

