//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@interface DCDEmbedComponent : CKCompositeComponent
{
}

+ (id)newWithEmbed:(id)arg1 context:(id)arg2;
+ (id)borderComponent:(id)arg1;
+ (id)backgroundComponent:(_Bool)arg1;
+ (id)footerComponentWithEmbed:(id)arg1 inset:(struct UIEdgeInsets)arg2;
+ (id)fieldsComponentWithEmbed:(id)arg1 inset:(struct UIEdgeInsets)arg2;
+ (id)providerComponentWithEmbed:(id)arg1 inset:(struct UIEdgeInsets)arg2;
+ (id)authorComponentWithEmbed:(id)arg1 inset:(struct UIEdgeInsets)arg2;
+ (id)titleComponentWithEmbed:(id)arg1 inset:(struct UIEdgeInsets)arg2;
+ (id)baseTitleComponentWithAttributedString:(id)arg1;
+ (id)descriptionComponentWithEmbed:(id)arg1 inset:(struct UIEdgeInsets)arg2;
+ (vector_89ce9f02)markdownWithContent:(id)arg1 options:(id)arg2;
- (void)handleTap:(id)arg1 context:(id)arg2;

@end

