//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RCTBridgeModule.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface DCDPOPAnimationManager : NSObject <RCTBridgeModule>
{
    RCTBridge *_bridge;
    NSMutableDictionary *_internalAnimations;
}

+ (id)__rct_export__1662;
+ (id)__rct_export__1491;
+ (id)__rct_export__730;
+ (void)load;
+ (id)moduleName;
@property(retain, nonatomic) NSMutableDictionary *internalAnimations; // @synthesize internalAnimations=_internalAnimations;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void).cxx_destruct;
- (void)removeAnimation:(id)arg1 animation:(id)arg2;
- (void)addAnimation:(id)arg1 animation:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)createAnimationInternal:(id)arg1 typeName:(id)arg2 attrs:(id)arg3;
- (id)constantsToExport;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

