//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSDictionary;

@interface DCDSeparatorButton : UIButton
{
    NSDictionary *_action;
}

@property(retain, nonatomic) NSDictionary *action; // @synthesize action=_action;
- (void).cxx_destruct;
- (void)setup:(id)arg1;

@end

