//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@interface DCDThumbnailComponent : CKCompositeComponent
{
}

+ (id)newWithThumbnail:(id)arg1 constrainedSize:(struct CGSize)arg2 context:(id)arg3 type:(id)arg4;
+ (id)newWithThumbnail:(id)arg1 constrainedSize:(struct CGSize)arg2 context:(id)arg3;
- (void)handleTap:(id)arg1;

@end

