//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTEventEmitter.h"

#import "RCTBridgeModule.h"
#import "RCTInvalidating.h"

@class NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface DCDVoiceEngine : RCTEventEmitter <RCTBridgeModule, RCTInvalidating>
{
    _Bool _shouldForwardVADLevelEventsToJavaScript;
    struct Discord *_discord;
    RCTBridge *_bridge;
}

+ (id)__rct_export__53622;
+ (id)__rct_export__53221;
+ (id)__rct_export__52820;
+ (id)__rct_export__52219;
+ (id)__rct_export__51818;
+ (id)__rct_export__51217;
+ (id)__rct_export__49516;
+ (id)__rct_export__49115;
+ (id)__rct_export__42914;
+ (id)__rct_export__42513;
+ (id)__rct_export__42112;
+ (id)__rct_export__41711;
+ (id)__rct_export__41010;
+ (id)__rct_export__4029;
+ (id)__rct_export__3958;
+ (id)__rct_export__3887;
+ (id)__rct_export__3816;
+ (id)__rct_export__3535;
+ (id)__rct_export__3394;
+ (id)__rct_export__3313;
+ (id)__rct_export__1952;
+ (id)__rct_export__1851;
+ (id)__rct_export__1550;
+ (id)convertDeviceDescriptions:(const vector_868a1150 *)arg1;
+ (void)load;
+ (id)moduleName;
@property _Bool shouldForwardVADLevelEventsToJavaScript; // @synthesize shouldForwardVADLevelEventsToJavaScript=_shouldForwardVADLevelEventsToJavaScript;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
@property struct Discord *discord; // @synthesize discord=_discord;
- (void).cxx_destruct;
- (void)setKeepAliveChannel:(_Bool)arg1;
- (void)setPTTActive:(_Bool)arg1;
- (void)setOutputDevice:(int)arg1;
- (void)getOutputDevices:(CDUnknownBlockType)arg1;
- (void)setInputDevice:(int)arg1;
- (void)getInputDevices:(CDUnknownBlockType)arg1;
- (void)setEmitPTTScanCodes:(_Bool)arg1;
- (void)setEmitVADLevel:(_Bool)arg1;
- (void)setInputMode:(int)arg1 options:(id)arg2;
- (void)setDuckingPreference:(_Bool)arg1;
- (void)setOutputVolume:(float)arg1;
- (void)setInputVolume:(float)arg1;
- (void)setSelfDeafen:(_Bool)arg1;
- (void)setSelfMute:(_Bool)arg1;
- (void)setLocalMute:(id)arg1 isMuted:(_Bool)arg2;
- (void)setLocalVolume:(id)arg1 scaling:(float)arg2;
- (void)destroyUser:(id)arg1;
- (void)mergeUsers:(id)arg1;
- (void)getEncryptionModes:(CDUnknownBlockType)arg1;
- (void)setEncodingBitRate:(int)arg1;
- (void)setTransportOptions:(id)arg1;
- (void)destroyTransport;
- (void)createTransport:(unsigned long long)arg1 userId:(id)arg2 serverIp:(id)arg3 port:(int)arg4 callback:(CDUnknownBlockType)arg5;
- (void)handleDeviceChangedChanged:(id)arg1;
- (void)handleVoiceLevelChanged:(id)arg1;
- (void)handlePTTSystemInputEvent:(id)arg1;
- (void)handleSpeakingStatusChanged:(id)arg1;
- (id)supportedEvents;
- (void)invalidate;
- (_Bool)isValid;
- (id)constantsToExport;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(readonly) Class superclass;

@end

