//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface HNKDiskCache : NSObject
{
    NSString *_directory;
    unsigned long long _capacity;
    unsigned long long _size;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) unsigned long long size; // @synthesize size=_size;
@property(nonatomic) unsigned long long capacity; // @synthesize capacity=_capacity;
- (void).cxx_destruct;
- (void)syncSetData:(id)arg1 forKey:(id)arg2;
- (void)removeFileAtPath:(id)arg1;
- (id)pathForKey:(id)arg1;
- (void)controlCapacity;
- (void)calculateSize;
- (void)enumerateDataByAccessDateUsingBlock:(CDUnknownBlockType)arg1;
- (void)removeAllData;
- (void)removeDataForKey:(id)arg1;
- (_Bool)dataExistsForKey:(id)arg1;
- (void)fetchDataForKey:(id)arg1 asynchronously:(_Bool)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)fetchDataForKey:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)setData:(id)arg1 forKey:(id)arg2;
- (id)initWithDirectory:(id)arg1 capacity:(unsigned long long)arg2;

@end

