//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HNKFetcher.h"

@class NSString, UIImage;

@interface HNKSimpleFetcher : NSObject <HNKFetcher>
{
    NSString *_key;
    UIImage *_image;
}

- (void).cxx_destruct;
- (void)fetchImageWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSString *key;
- (id)initWithKey:(id)arg1 image:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

