//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface LinkView : UIView
{
    NSString *_URL;
}

@property(retain, nonatomic) NSString *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;

@end

