//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVPlayerViewController.h"

@interface RCTVideoPlayerViewController : AVPlayerViewController
{
    id <RCTVideoPlayerViewControllerDelegate> _rctDelegate;
}

@property(nonatomic) __weak id <RCTVideoPlayerViewControllerDelegate> rctDelegate; // @synthesize rctDelegate=_rctDelegate;
- (void).cxx_destruct;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;

@end

