//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTViewManager.h"

@class RCTBridge;

@interface RCTVideoManager : RCTViewManager
{
    RCTBridge *_bridge;
}

+ (id)propConfig_fullscreen;
+ (id)propConfig_currentTime;
+ (id)propConfig_seek;
+ (id)propConfig_rate;
+ (id)propConfig_volume;
+ (id)propConfig_controls;
+ (id)propConfig_muted;
+ (id)propConfig_paused;
+ (id)propConfig_repeat;
+ (id)propConfig_resizeMode;
+ (id)propConfig_src;
+ (void)load;
+ (id)moduleName;
- (void)setBridge:(id)arg1;
- (id)bridge;
- (void).cxx_destruct;
- (id)constantsToExport;
- (id)methodQueue;
- (id)customDirectEventTypes;
- (id)view;

@end

