//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoDataOutput, NSString;

@interface RTCAVFoundationVideoCapturerInternal : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    AVCaptureDeviceInput *_frontCameraInput;
    AVCaptureDeviceInput *_backCameraInput;
    AVCaptureVideoDataOutput *_videoDataOutput;
    struct AVFoundationVideoCapturer *_capturer;
    _Bool _orientationHasChanged;
    _Bool _isRunning;
    _Bool _useBackCamera;
    AVCaptureSession *_captureSession;
}

@property(readonly, nonatomic) _Bool isRunning; // @synthesize isRunning=_isRunning;
- (void).cxx_destruct;
- (void)updateSessionInputForUseBackCamera:(_Bool)arg1;
- (void)updateOrientation;
- (void)deviceOrientationDidChange:(id)arg1;
- (id)backCameraInput;
- (id)frontCameraInput;
- (id)videoCaptureDeviceForPosition:(long long)arg1;
- (id)videoDataOutput;
- (_Bool)setupCaptureSession;
- (void)captureOutput:(id)arg1 didDropSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)stop;
- (void)start;
@property(nonatomic) _Bool useBackCamera; // @synthesize useBackCamera=_useBackCamera;
@property(readonly, nonatomic) _Bool canUseBackCamera;
@property(readonly, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
- (void)dealloc;
- (id)initWithCapturer:(struct AVFoundationVideoCapturer *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

