//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GLKViewDelegate.h"
#import "RTCVideoRenderer.h"

@class GLKView, NSString, RTCDisplayLinkTimer, RTCOpenGLVideoRenderer, RTCVideoFrame;

@interface RTCEAGLVideoView : UIView <GLKViewDelegate, RTCVideoRenderer>
{
    RTCDisplayLinkTimer *_timer;
    _Bool _isDirty;
    id <RTCEAGLVideoViewDelegate> _delegate;
    RTCVideoFrame *_videoFrame;
    GLKView *_glkView;
    RTCOpenGLVideoRenderer *_glRenderer;
}

@property(readonly, nonatomic) RTCOpenGLVideoRenderer *glRenderer; // @synthesize glRenderer=_glRenderer;
@property(readonly, nonatomic) GLKView *glkView; // @synthesize glkView=_glkView;
@property(retain) RTCVideoFrame *videoFrame; // @synthesize videoFrame=_videoFrame;
@property(nonatomic) __weak id <RTCEAGLVideoViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)willResignActive;
- (void)didBecomeActive;
- (void)teardownGL;
- (void)setupGL;
- (void)displayLinkTimerDidFire;
- (void)renderFrame:(id)arg1;
- (void)setSize:(struct CGSize)arg1;
- (void)glkView:(id)arg1 drawInRect:(struct CGRect)arg2;
- (void)layoutSubviews;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (void)setNeedsDisplay;
- (void)dealloc;
- (void)configure;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

