//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RTCIceCandidate : NSObject
{
    int _sdpMLineIndex;
    NSString *_sdpMid;
    NSString *_sdp;
}

@property(readonly, nonatomic) NSString *sdp; // @synthesize sdp=_sdp;
@property(readonly, nonatomic) int sdpMLineIndex; // @synthesize sdpMLineIndex=_sdpMLineIndex;
@property(readonly, nonatomic) NSString *sdpMid; // @synthesize sdpMid=_sdpMid;
- (void).cxx_destruct;
@property(readonly, nonatomic) unique_ptr_eddc2ff2 nativeCandidate;
- (id)initWithNativeCandidate:(const struct IceCandidateInterface *)arg1;
- (id)description;
- (id)initWithSdp:(id)arg1 sdpMLineIndex:(int)arg2 sdpMid:(id)arg3;

@end

