//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface RTCMediaConstraints : NSObject
{
    NSDictionary *_mandatory;
    NSDictionary *_optional;
}

+ (struct Constraints)nativeConstraintsForConstraints:(id)arg1;
- (void).cxx_destruct;
- (unique_ptr_ba2c75b1)nativeConstraints;
- (id)description;
- (id)initWithMandatoryConstraints:(id)arg1 optionalConstraints:(id)arg2;

@end

