//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, RTCSessionDescription;

@interface RTCPeerConnection : NSObject
{
    NSMutableArray *_localStreams;
    struct unique_ptr<webrtc::PeerConnectionDelegateAdapter, std::__1::default_delete<webrtc::PeerConnectionDelegateAdapter>> _observer;
    scoped_refptr_1f0d680a _peerConnection;
    id <RTCPeerConnectionDelegate> _delegate;
}

+ (int)nativeStatsOutputLevelForLevel:(long long)arg1;
+ (id)stringForIceGatheringState:(long long)arg1;
+ (long long)iceGatheringStateForNativeState:(int)arg1;
+ (int)nativeIceGatheringStateForState:(long long)arg1;
+ (id)stringForIceConnectionState:(long long)arg1;
+ (long long)iceConnectionStateForNativeState:(int)arg1;
+ (int)nativeIceConnectionStateForState:(long long)arg1;
+ (id)stringForSignalingState:(long long)arg1;
+ (long long)signalingStateForNativeState:(int)arg1;
+ (int)nativeSignalingStateForState:(long long)arg1;
@property(nonatomic) __weak id <RTCPeerConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) scoped_refptr_1f0d680a nativePeerConnection;
@property(readonly, nonatomic) NSArray *receivers;
@property(readonly, nonatomic) NSArray *senders;
- (id)senderWithKind:(id)arg1 streamId:(id)arg2;
- (void)setRemoteDescription:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setLocalDescription:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)answerForConstraints:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)offerForConstraints:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)removeStream:(id)arg1;
- (void)addStream:(id)arg1;
- (void)addIceCandidate:(id)arg1;
- (void)close;
- (_Bool)setConfiguration:(id)arg1;
@property(readonly, nonatomic) long long iceGatheringState;
@property(readonly, nonatomic) long long iceConnectionState;
@property(readonly, nonatomic) long long signalingState;
@property(readonly, nonatomic) RTCSessionDescription *remoteDescription;
@property(readonly, nonatomic) RTCSessionDescription *localDescription;
@property(readonly, nonatomic) NSArray *localStreams;
- (id)initWithFactory:(id)arg1 configuration:(id)arg2 constraints:(id)arg3 delegate:(id)arg4;
- (id)dataChannelForLabel:(id)arg1 configuration:(id)arg2;
- (void)statsForTrack:(id)arg1 statsOutputLevel:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;

@end

