//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RTCVideoFrame : NSObject
{
    struct unique_ptr<cricket::VideoFrame, std::__1::default_delete<cricket::VideoFrame>> _videoFrame;
    scoped_refptr_30488dd1 _i420Buffer;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) scoped_refptr_30488dd1 i420Buffer;
- (id)initWithNativeFrame:(const struct VideoFrame *)arg1;
- (void)convertBufferIfNeeded;
@property(readonly, nonatomic) struct __CVBuffer *nativeHandle;
@property(readonly, nonatomic) long long timeStamp;
@property(readonly, nonatomic) int vPitch;
@property(readonly, nonatomic) int uPitch;
@property(readonly, nonatomic) int yPitch;
@property(readonly, nonatomic) const char *vPlane;
@property(readonly, nonatomic) const char *uPlane;
@property(readonly, nonatomic) const char *yPlane;
@property(readonly, nonatomic) unsigned long long chromaHeight;
@property(readonly, nonatomic) unsigned long long chromaWidth;
@property(readonly, nonatomic) unsigned long long height;
@property(readonly, nonatomic) unsigned long long width;

@end

