//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (hnk_utils)
- (id)hnk_imageByCenteringToSize:(struct CGSize)arg1;
- (id)hnk_imageByScalingToSize:(struct CGSize)arg1;
- (_Bool)hnk_hasAlpha;
- (id)hnk_decompressedImage;
- (struct CGSize)hnk_aspectFitSizeForSize:(struct CGSize)arg1;
- (id)hnk_dataWithCompressionQuality:(double)arg1;
- (struct CGSize)hnk_aspectFillSizeForSize:(struct CGSize)arg1;
@end

